import { and, desc, eq, isNull } from "drizzle-orm";
import { memories } from "@bobai/db";
let dbPromise: Promise<typeof import("@bobai/db").db | null> | null = null;
async function getDb() { if (!process.env.DATABASE_URL) return null; if (!dbPromise) dbPromise = import("@bobai/db").then((module) => module.db).catch(() => null); return dbPromise; }
export function isSensitiveMemory(value: string) { return /\b(password|passcode|otp|one[- ]time code|api key|secret key|private key|credit card|cvv|cvc|bank account|routing number)\b/i.test(value); }
export async function dbRemember(input: { workspaceId: string; userId?: string; key: string; value: string }) { if (isSensitiveMemory(input.value)) return false; const db = await getDb(); if (!db) return false; const existing = await db.select({ id: memories.id }).from(memories).where(and(eq(memories.workspaceId, input.workspaceId), input.userId ? eq(memories.userId, input.userId) : undefined, eq(memories.content, input.value), isNull(memories.deletedAt))).limit(1); if (existing.length) { await db.update(memories).set({ category: input.key, updatedAt: new Date(), lastAccessedAt: new Date() }).where(eq(memories.id, existing[0].id)); return true; } await db.insert(memories).values({ workspaceId: input.workspaceId, userId: input.userId, category: input.key, content: input.value, summary: input.key, importance: input.key === "explicit memory" ? 70 : 50 }); return true; }
export async function dbRecallAll(workspaceId: string, userId?: string) { const db = await getDb(); if (!db) return null; const rows = await db.select().from(memories).where(and(eq(memories.workspaceId, workspaceId), userId ? eq(memories.userId, userId) : undefined, eq(memories.isArchived, false), isNull(memories.deletedAt))).orderBy(desc(memories.isPinned), desc(memories.importance), desc(memories.updatedAt)); return rows; }
export async function dbUpdateMemory(id: string, workspaceId: string, userId: string, changes: { category?: string; content?: string; isPinned?: boolean; isArchived?: boolean; importance?: number }) { const db = await getDb(); if (!db || (changes.content && isSensitiveMemory(changes.content))) return null; const [row] = await db.update(memories).set({ ...changes, updatedAt: new Date() }).where(and(eq(memories.id, id), eq(memories.workspaceId, workspaceId), eq(memories.userId, userId), isNull(memories.deletedAt))).returning(); return row ?? null; }
export async function dbDeleteMemory(id: string, workspaceId: string, userId: string) { const db = await getDb(); if (!db) return false; const [row] = await db.update(memories).set({ deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(memories.id, id), eq(memories.workspaceId, workspaceId), eq(memories.userId, userId), isNull(memories.deletedAt))).returning({ id: memories.id }); return Boolean(row); }
export async function dbClearMemory(workspaceId: string, userId?: string) { const db = await getDb(); if (!db) return false; await db.update(memories).set({ deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(memories.workspaceId, workspaceId), userId ? eq(memories.userId, userId) : undefined, isNull(memories.deletedAt))); return true; }
