"use client";
import { type FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import BobLogo from "@/components/BobLogo";
import { register } from "@/lib/auth";
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; const usernamePattern = /^[A-Za-z0-9_]{3,32}$/;
export default function SignupPage() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [acceptedTerms, setAcceptedTerms] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function handleSignup(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const cleanUsername = username.trim(); const cleanEmail = email.trim().toLowerCase(); if (!usernamePattern.test(cleanUsername)) return setError("username must be 3-32 letters, numbers, or underscores"); if (!emailPattern.test(cleanEmail)) return setError("enter a valid email address"); if (password.length < 6) return setError("password must be at least 6 characters"); if (password.length > 128) return setError("password must be 128 characters or fewer"); if (!acceptedTerms) return setError("you must accept the Terms of Service to create an account"); setLoading(true); const result = await register(cleanUsername, cleanEmail, password, { termsAccepted: true, termsVersion: "2026-09-08" }); setLoading(false); if (!result.ok) { setError(result.error || "account could not be created"); return; } router.push(`/verify-otp?email=${encodeURIComponent(cleanEmail)}&created=1`); }
  return <main className="min-h-screen bg-[#080a0d] px-5 py-10 text-white"><div className="mx-auto flex min-h-[calc(100vh-5rem)] w-full max-w-md flex-col justify-center"><Link href="/" className="mb-10 flex items-center gap-3 self-start"><BobLogo /><div><p className="text-lg font-semibold">Bob AI</p><p className="text-xs text-white/40">your AI workspace</p></div></Link><div className="rounded-[28px] border border-white/10 bg-white/[0.035] p-6 shadow-2xl shadow-black/30 sm:p-8"><h1 className="text-3xl font-black tracking-tight">create account</h1><p className="mt-2 text-sm text-white/50">Set up your BobAI account.</p><form onSubmit={handleSignup} className="mt-7 space-y-4"><input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="username" autoComplete="username" minLength={3} maxLength={32} required className="w-full rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3.5 outline-none focus:border-cyan-300/40" /><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" placeholder="email" autoComplete="email" required className="w-full rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3.5 outline-none focus:border-cyan-300/40" /><input value={password} onChange={(event) => setPassword(event.target.value)} type="password" placeholder="password" autoComplete="new-password" minLength={6} maxLength={128} required className="w-full rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3.5 outline-none focus:border-cyan-300/40" /><p className="text-xs text-white/35">6–128 characters. Choose something you can remember.</p><label className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-3 text-sm text-white/55"><input type="checkbox" checked={acceptedTerms} onChange={(event) => setAcceptedTerms(event.target.checked)} className="mt-1 h-4 w-4 shrink-0" required /><span>I agree to the <Link href="/terms" target="_blank" className="text-cyan-300 hover:text-cyan-200">Terms of Service</Link> and acknowledge the <Link href="/privacy" target="_blank" className="text-cyan-300 hover:text-cyan-200">Privacy Policy</Link>.</span></label>{error && <p className="text-sm text-red-400">{error}</p>}<button type="submit" disabled={loading || !acceptedTerms} className="w-full rounded-2xl bg-white py-3 font-bold text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-50">{loading ? "creating..." : "create account"}</button></form><div className="mt-6 flex items-center justify-between text-sm text-white/45"><Link href="/login" className="hover:text-white">already have an account?</Link><Link href="/verify-otp" className="hover:text-white">verify email</Link></div></div></div></main>;
}
