"use client";
import { useEffect,useRef,useState } from "react";
import { Mic,Square,Volume2 } from "lucide-react";
import { synthesizeSpeech,transcribeAudio } from "@/lib/voice";

type Props={onTranscript:(text:string)=>void;disabled?:boolean;readAloudText?:string};
export default function VoiceButton({onTranscript,disabled=false,readAloudText}:Props){const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const [recording,setRecording]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>()=>{recorder.current?.stop()},[]);
 async function start(){setError("");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":MediaRecorder.isTypeSupported("audio/webm")?"audio/webm":"audio/wav";const r=new MediaRecorder(stream,{mimeType:mime});chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);setBusy(true);try{const text=await transcribeAudio(new Blob(chunks.current,{type:mime}));onTranscript(text)}catch(e){setError(e instanceof Error?e.message:"transcription failed")}finally{setBusy(false)}};recorder.current=r;r.start();setRecording(true)}catch(e){setError(e instanceof Error?e.message:"microphone unavailable")}}
 function stop(){recorder.current?.stop()}
 async function speak(){if(!readAloudText?.trim())return;setError("");setBusy(true);try{const result=await synthesizeSpeech(readAloudText);const raw=atob(result.audio);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:result.mimeType}));const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play()}catch(e){setError(e instanceof Error?e.message:"speech playback failed")}finally{setBusy(false)}}
 return <div className="flex items-center gap-2">{readAloudText!==undefined&&<button type="button" onClick={speak} disabled={disabled||busy||!readAloudText.trim()} aria-label="read response aloud" title="read response aloud" className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/[0.07] bg-white/[0.025] text-white/50 hover:border-cyan-300/25 hover:text-cyan-200 disabled:opacity-30"><Volume2 className="h-4 w-4"/></button>}<button type="button" onClick={recording?stop:start} disabled={disabled||busy} aria-label={recording?"stop recording":"voice input"} title={recording?"stop recording":"voice input"} className={`flex h-9 w-9 items-center justify-center rounded-xl border ${recording?"border-cyan-300/50 bg-cyan-300/10 text-cyan-200":"border-white/[0.07] bg-white/[0.025] text-white/50 hover:border-cyan-300/25 hover:text-cyan-200"} disabled:opacity-30`}>{recording?<Square className="h-3.5 w-3.5"/>:<Mic className="h-4 w-4"/>}</button>{error&&<span role="status" className="max-w-48 truncate text-[10px] text-red-300/80">{error}</span>}</div>}
