import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { and, eq, gt, isNull } from "drizzle-orm";
import { db, sessions, users } from "@bobai/db";
import { enforcePasswordPolicy } from "./passwordPolicy.js";
import { recordAudit } from "./audit.js";
const scrypt = (password: string, salt: Buffer, keylen: number, options: Parameters<typeof scryptCallback>[3]) => new Promise<Buffer>((resolve, reject) => scryptCallback(password, salt, keylen, options, (error, derived) => error ? reject(error) : resolve(derived as Buffer)));
const ACCESS_TTL_MS = 15 * 60 * 1000; const REFRESH_TTL_MS = 30 * 24 * 60 * 60 * 1000; const SCRYPT = { N: 1 << 14, r: 8, p: 1, maxmem: 32 * 1024 * 1024 };
const hashToken = (value: string) => createHash("sha256").update(value).digest("hex"); const token = () => randomBytes(32).toString("base64url");
async function hashPassword(password: string) { const salt = randomBytes(16); const derived = await scrypt(password, salt, 64, SCRYPT); return `${salt.toString("base64url")}.${derived.toString("base64url")}`; }
async function verifyPassword(password: string, stored: string | null) { if (!stored) return false; const [saltText, hashText] = stored.split("."); if (!saltText || !hashText) return false; const expected = Buffer.from(hashText, "base64url"); const actual = await scrypt(password, Buffer.from(saltText, "base64url"), expected.length, SCRYPT); return actual.length === expected.length && timingSafeEqual(actual, expected); }
export async function createUser(email: string, username: string, password: string) { const policyError = await enforcePasswordPolicy(password); if (policyError) { const error = new Error(policyError); (error as Error & { code?: string }).code = "PASSWORD_POLICY"; throw error; } const passwordHash = await hashPassword(password); const [user] = await db.insert(users).values({ email, username, passwordHash }).returning({ id: users.id, email: users.email, username: users.username, displayName: users.displayName, avatarUrl: users.avatarUrl, role: users.role }); if (!user) throw new Error("user creation failed"); return user; }
export async function login(email: string, password: string, metadata?: Record<string, unknown>) { const [user] = await db.select().from(users).where(eq(users.email, email)).limit(1); if (!user || !(await verifyPassword(password, user.passwordHash))) { await recordAudit({ action: "login_failed", resourceType: "authentication", metadata: { email: email.slice(0, 254) } }); return null; } if (!user.emailVerifiedAt) { await recordAudit({ action: "login_blocked_unverified", resourceType: "authentication", userId: user.id }); return { requiresVerification: true as const }; } const session = await issueSession(user.id, metadata); await recordAudit({ action: "login_succeeded", resourceType: "session", resourceId: session.sessionId, userId: user.id, sessionId: session.sessionId, metadata: { userAgent: metadata?.userAgent } }); return session; }
export async function issueSession(userId: string, metadata?: Record<string, unknown>) { const accessToken = token(); const refreshToken = token(); const now = Date.now(); const [session] = await db.insert(sessions).values({ userId, accessTokenHash: hashToken(accessToken), refreshTokenHash: hashToken(refreshToken), accessExpiresAt: new Date(now + ACCESS_TTL_MS), expiresAt: new Date(now + REFRESH_TTL_MS), metadata }).returning({ id: sessions.id }); if (!session) throw new Error("session creation failed"); return { sessionId: session.id, accessToken, refreshToken, expiresIn: ACCESS_TTL_MS / 1000 }; }
export async function authenticateAccessToken(accessToken: string) { const [result] = await db.select({ session: sessions, user: users }).from(sessions).innerJoin(users, eq(users.id, sessions.userId)).where(and(eq(sessions.accessTokenHash, hashToken(accessToken)), eq(sessions.isActive, true), isNull(sessions.revokedAt), gt(sessions.accessExpiresAt, new Date()))).limit(1); if (!result) return null; await db.update(sessions).set({ lastUsedAt: new Date(), updatedAt: new Date() }).where(eq(sessions.id, result.session.id)); return result.user; }
export async function refresh(refreshToken: string) { const hash = hashToken(refreshToken); const now = new Date(); const [session] = await db.update(sessions).set({ revokedAt: now, isActive: false, updatedAt: now }).where(and(eq(sessions.refreshTokenHash, hash), eq(sessions.isActive, true), isNull(sessions.revokedAt), gt(sessions.expiresAt, now))).returning({ userId: sessions.userId, id: sessions.id }); if (!session) return null; const next = await issueSession(session.userId); await recordAudit({ action: "session_refreshed", resourceType: "session", resourceId: next.sessionId, userId: session.userId, sessionId: next.sessionId, metadata: { replacedSessionId: session.id } }); return next; }
export async function revoke(refreshToken: string) { await db.update(sessions).set({ revokedAt: new Date(), isActive: false, updatedAt: new Date() }).where(eq(sessions.refreshTokenHash, hashToken(refreshToken))); }
