import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { and, eq, gt, isNull } from "drizzle-orm";
import { db, sessions, users } from "@bobai/db";
import { enforcePasswordPolicy } from "./passwordPolicy.js";
import { recordAudit } from "./audit.js";
import { createMfaChallenge, userMfaStatus, verifyMfaChallenge } from "./mfa.js";
const scrypt = (password: string, salt: Buffer, keylen: number, options: Parameters<typeof scryptCallback>[3]) => new Promise<Buffer>((resolve, reject) => scryptCallback(password, salt, keylen, options, (error, derived) => error ? reject(error) : resolve(derived as Buffer)));
const ACCESS_TTL_MS = 15 * 60 * 1000; const REFRESH_TTL_MS = 30 * 24 * 60 * 60 * 1000; const SCRYPT = { N: 1 << 14, r: 8, p: 1, maxmem: 32 * 1024 * 1024 };
const hashToken = (value: string) => createHash("sha256").update(value).digest("hex"); const token = () => randomBytes(32).toString("base64url");
async function hashPassword(password: string) { const salt = randomBytes(16); const derived = await scrypt(password, salt, 64, SCRYPT); return `${salt.toString("base64url")}.${derived.toString("base64url")}`; }
async function verifyPassword(password: string, stored: string | null) { if (!stored) return false; const [saltText, hashText] = stored.split("."); if (!saltText || !hashText) return false; const expected = Buffer.from(hashText, "base64url"); const actual = await scrypt(password, Buffer.from(saltText, "base64url"), expected.length, SCRYPT); return actual.length === expected.length && timingSafeEqual(actual, expected); }
function isUniqueViolation(error: unknown): boolean { let current: unknown = error; for (let depth = 0; depth < 5; depth += 1) { if (current && typeof current === "object" && "code" in current && (current as { code?: unknown }).code === "23505") return true; current = current && typeof current === "object" && "cause" in current ? (current as { cause?: unknown }).cause : undefined; } return false; }
export async function createUser(email: string, username: string, password: string, legal?: { termsAccepted: boolean; termsVersion: string }) { if (!legal?.termsAccepted || !legal.termsVersion) { const error = new Error("acceptance of the Terms of Service is required"); (error as Error & { code?: string }).code = "TERMS_REQUIRED"; throw error; } const policyError = await enforcePasswordPolicy(password); if (policyError) { const error = new Error(policyError); (error as Error & { code?: string }).code = "PASSWORD_POLICY"; throw error; } const passwordHash = await hashPassword(password); const acceptedAt = new Date(); try { const [user] = await db.insert(users).values({ email, username, passwordHash, termsAcceptedAt: acceptedAt, termsVersion: legal.termsVersion }).returning({ id: users.id, email: users.email, username: users.username, displayName: users.displayName, avatarUrl: users.avatarUrl, role: users.role }); if (!user) throw new Error("user creation failed"); await recordAudit({ action: "terms_accepted", resourceType: "user", resourceId: user.id, userId: user.id, metadata: { termsVersion: legal.termsVersion, acceptedAt: acceptedAt.toISOString() } }); return user; } catch (error) { if (isUniqueViolation(error)) { const conflict = new Error("account details are already in use"); (conflict as Error & { code?: string }).code = "ACCOUNT_EXISTS"; throw conflict; } throw error; } }
export async function login(email: string, password: string, metadata?: Record<string, unknown>) { const [user] = await db.select().from(users).where(eq(users.email, email)).limit(1); if (!user || user.deletedAt || !(await verifyPassword(password, user.passwordHash))) { await recordAudit({ action: "login_failed", resourceType: "authentication" }); return null; } if (!user.emailVerifiedAt) { await recordAudit({ action: "login_blocked_unverified", resourceType: "authentication", userId: user.id }); return null; } if (user.mfaEnabled && user.mfaSecretEncrypted) { const challengeToken = await createMfaChallenge(user.id); await recordAudit({ action: "mfa_challenge_created", resourceType: "authentication", userId: user.id }); return { mfaRequired: true as const, challengeToken }; } const session = await issueSession(user.id, metadata); await recordAudit({ action: "login_succeeded", resourceType: "session", resourceId: session.sessionId, userId: user.id, sessionId: session.sessionId, metadata: { userAgent: metadata?.userAgent } }); return session; }
export async function completeMfaLogin(challengeToken: string, code: string, metadata?: Record<string, unknown>) { const userId = await verifyMfaChallenge(challengeToken, code); if (!userId) return null; const session = await issueSession(userId, metadata); await recordAudit({ action: "login_succeeded_mfa", resourceType: "session", resourceId: session.sessionId, userId, sessionId: session.sessionId, metadata: { userAgent: metadata?.userAgent } }); return session; }
export async function issueSession(userId: string, metadata?: Record<string, unknown>, familyId: `${string}-${string}-${string}-${string}-${string}` = randomUUID() as `${string}-${string}-${string}-${string}-${string}`) { const accessToken = token(); const refreshToken = token(); const now = Date.now(); const [session] = await db.insert(sessions).values({ userId, familyId, accessTokenHash: hashToken(accessToken), refreshTokenHash: hashToken(refreshToken), accessExpiresAt: new Date(now + ACCESS_TTL_MS), expiresAt: new Date(now + REFRESH_TTL_MS), metadata }).returning({ id: sessions.id }); if (!session) throw new Error("session creation failed"); return { sessionId: session.id, accessToken, refreshToken, expiresIn: ACCESS_TTL_MS / 1000 }; }
export async function authenticateAccessToken(accessToken: string) { const [result] = await db.select({ sessionId: sessions.id, userId: users.id, email: users.email, username: users.username, displayName: users.displayName, avatarUrl: users.avatarUrl, role: users.role }).from(sessions).innerJoin(users, eq(users.id, sessions.userId)).where(and(eq(sessions.accessTokenHash, hashToken(accessToken)), eq(sessions.isActive, true), isNull(sessions.revokedAt), isNull(users.deletedAt), gt(sessions.accessExpiresAt, new Date()))).limit(1); if (!result) return null; await db.update(sessions).set({ lastUsedAt: new Date(), updatedAt: new Date() }).where(eq(sessions.id, result.sessionId)); return { id: result.userId, email: result.email, username: result.username, displayName: result.displayName, avatarUrl: result.avatarUrl, role: result.role }; }
export async function refresh(refreshToken: string) {
  const hash = hashToken(refreshToken);
  const now = new Date();
  const [session] = await db.update(sessions).set({ revokedAt: now, isActive: false, updatedAt: now }).where(and(eq(sessions.refreshTokenHash, hash), eq(sessions.isActive, true), isNull(sessions.revokedAt), gt(sessions.expiresAt, now))).returning({ userId: sessions.userId, id: sessions.id, familyId: sessions.familyId });
  if (!session) {
    const [reused] = await db.select({ userId: sessions.userId, familyId: sessions.familyId }).from(sessions).where(eq(sessions.refreshTokenHash, hash)).limit(1);
    if (reused?.familyId) {
      await db.update(sessions).set({ revokedAt: now, isActive: false, updatedAt: now }).where(and(eq(sessions.familyId, reused.familyId), eq(sessions.isActive, true), isNull(sessions.revokedAt)));
      await recordAudit({ action: "refresh_token_reuse_detected", resourceType: "session_family", userId: reused.userId, metadata: { familyId: reused.familyId } });
    }
    return null;
  }
  const [user] = await db.select({ id: users.id }).from(users).where(and(eq(users.id, session.userId), isNull(users.deletedAt))).limit(1);
  if (!user) return null;
  const next = await issueSession(session.userId, undefined, session.familyId as `${string}-${string}-${string}-${string}-${string}`);
  await recordAudit({ action: "session_refreshed", resourceType: "session", resourceId: next.sessionId, userId: session.userId, sessionId: next.sessionId, metadata: { replacedSessionId: session.id, familyId: session.familyId } });
  return next;
}
export async function revoke(refreshToken: string) { await db.update(sessions).set({ revokedAt: new Date(), isActive: false, updatedAt: new Date() }).where(eq(sessions.refreshTokenHash, hashToken(refreshToken))); }
export async function verifyCurrentPassword(userId: string, password: string) { const [user] = await db.select({ passwordHash: users.passwordHash }).from(users).where(and(eq(users.id, userId), isNull(users.deletedAt))).limit(1); return Boolean(user && await verifyPassword(password, user.passwordHash)); }
export async function changePassword(userId: string, currentPassword: string, nextPassword: string) { const policyError = await enforcePasswordPolicy(nextPassword); if (policyError) return { ok: false as const, error: policyError }; if (!await verifyCurrentPassword(userId, currentPassword)) return { ok: false as const, error: "current password is incorrect" }; const passwordHash = await hashPassword(nextPassword); await db.transaction(async (tx) => { await tx.update(users).set({ passwordHash, updatedAt: new Date() }).where(eq(users.id, userId)); await tx.update(sessions).set({ revokedAt: new Date(), isActive: false, updatedAt: new Date() }).where(and(eq(sessions.userId, userId), eq(sessions.isActive, true), isNull(sessions.revokedAt))); }); await recordAudit({ action: "password_changed", resourceType: "user", resourceId: userId, userId }); return { ok: true as const }; }
export { userMfaStatus };
