import { createHash } from "node:crypto";
import { specialistConfigured, specialistInfer } from "./specialistRuntime.js";
import { modelRuntime } from "./modelRuntime.js";
const MAX_INPUT=8000,DIMENSIONS=1536,SPECIALIST_DIMENSIONS=128;
function expand(v:number[]){const out=new Float64Array(DIMENSIONS);for(let i=0;i<DIMENSIONS;i++)out[i]=v[i%SPECIALIST_DIMENSIONS]*(1+((i/SPECIALIST_DIMENSIONS)|0)*0.0001);let n=0;for(const x of out)n+=x*x;n=Math.sqrt(n)||1;return Array.from(out,x=>x/n);}
function local(text:string){const v=new Float64Array(DIMENSIONS);const terms=text.normalize("NFKC").toLowerCase().split(/\s+/).filter(Boolean);for(const term of terms){const d=createHash("sha256").update(term).digest();for(let i=0;i<8;i++)v[d.readUInt16BE(i*2)%DIMENSIONS]+=d[i]/255-.5;}if(!terms.length)return Array.from(v);let n=0;for(const x of v)n+=x*x;n=Math.sqrt(n)||1;return Array.from(v,x=>x/n);}
export function embeddingsConfigured(){return true;}
export async function generateSpecialistEmbedding(text:string):Promise<number[]|null>{const input=text.trim().slice(0,MAX_INPUT);if(!input||!specialistConfigured("embedding"))return null;try{const release=await modelRuntime.acquire("bob-embed-0.1");try{const result=await specialistInfer("embedding",{text:input});if(Array.isArray(result.vector)&&result.vector.length===SPECIALIST_DIMENSIONS&&result.vector.every(x=>typeof x==="number"))return result.vector as number[];}finally{release();}}catch{}return null;}
export async function generateEmbedding(text:string):Promise<number[]|null>{const input=text.trim().slice(0,MAX_INPUT);if(!input)return null;const specialist=await generateSpecialistEmbedding(input);return specialist?expand(specialist):local(input);}
export async function rerank(query:number[],document:number[]){if(query.length!==SPECIALIST_DIMENSIONS||document.length!==SPECIALIST_DIMENSIONS||!specialistConfigured("reranking"))return null;try{const release=await modelRuntime.acquire("bob-reranker-0.1");try{const result=await specialistInfer("reranking",{query,document});return typeof result.score==="number"?Math.max(0,Math.min(1,result.score)):null;}finally{release();}}catch{return null;}}
export async function rerankText(query:string,document:string){const [q,d]=await Promise.all([generateSpecialistEmbedding(query),generateSpecialistEmbedding(document)]);return q&&d?rerank(q,d):null;}
