import { assertMediaPromptSafe } from "./mediaSafety.js";
type GeneratedImage = { url: string; prompt: string; index: number }; type LocalMediaProvider = { baseUrl: string; imagePath: string; videoPath: string }; type MediaOptions = { prompt: string; count?: number; inputImages?: string[]; width?: number; height?: number; durationSeconds?: number; aspectRatio?: string; seed?: number };
const MAX_INPUT_IMAGES = 4, MAX_PROMPT_LENGTH = 8000; function isLoopback(hostname: string) { const host = hostname.toLowerCase(); return host === "localhost" || host === "127.0.0.1" || host === "::1" || host === "[::1]"; }
function provider(): LocalMediaProvider | null { const baseUrl = process.env.BOBAI_LOCAL_MEDIA_URL?.trim(); if (!baseUrl) return null; const url = new URL(baseUrl); const developmentLoopback = process.env.NODE_ENV !== "production" && url.protocol === "http:" && isLoopback(url.hostname); if (url.protocol !== "https:" && !developmentLoopback) throw new Error("BOBAI_LOCAL_MEDIA_URL must use HTTPS outside local development"); if (!isLoopback(url.hostname)) throw new Error("BOBAI_LOCAL_MEDIA_URL must point to localhost or a loopback address"); return { baseUrl: url.origin, imagePath: process.env.BOBAI_LOCAL_IMAGE_PATH?.trim() || "/generate/image", videoPath: process.env.BOBAI_LOCAL_VIDEO_PATH?.trim() || "/generate/video" }; }
function normalizeImages(inputImages: string[] | undefined) { if (!inputImages) return []; if (!Array.isArray(inputImages) || inputImages.length > MAX_INPUT_IMAGES) throw new Error("up to 4 input images are supported"); return inputImages.filter((image) => typeof image === "string" && image.trim()).slice(0, MAX_INPUT_IMAGES); }
function safeMediaUrl(value: string) { try { const url = new URL(value); if (!["https:", "http:"].includes(url.protocol)) return null; return url.toString(); } catch { return null; } }
async function localGenerate(path: string, options: MediaOptions) { const config = provider(); if (!config) throw new Error("media generation provider is not configured"); assertMediaPromptSafe(options.prompt); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 120_000); try { const response = await fetch(new URL(path, config.baseUrl), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt: options.prompt, count: options.count ?? 1, inputImages: normalizeImages(options.inputImages), width: options.width, height: options.height, durationSeconds: options.durationSeconds, aspectRatio: options.aspectRatio, seed: options.seed }), signal: controller.signal, redirect: "error" }); if (!response.ok) throw new Error(`local media provider returned ${response.status}`); const contentLength = Number(response.headers.get("content-length")); if (Number.isFinite(contentLength) && contentLength > 10 * 1024 * 1024) throw new Error("local media provider response exceeds the 10 MB limit"); const body = await response.json() as { url?: unknown; urls?: unknown; data?: Array<{ url?: unknown }> }; const candidates = [typeof body.url === "string" ? body.url : "", ...(Array.isArray(body.urls) ? body.urls.filter((url): url is string => typeof url === "string") : []), ...(Array.isArray(body.data) ? body.data.map((item) => item?.url).filter((url): url is string => typeof url === "string") : [])]; const urls = candidates.map(safeMediaUrl).filter((url): url is string => Boolean(url)); if (!urls.length) throw new Error("local media provider returned no valid media URL"); return urls.slice(0, 4); } finally { clearTimeout(timer); } }
export async function generateImages(prompt: string, count = 4, inputImages?: string[]): Promise<GeneratedImage[]> { const normalized = prompt.trim(); if (!normalized) throw new Error("image prompt is required"); if (normalized.length > MAX_PROMPT_LENGTH) throw new Error("image prompt is too long"); assertMediaPromptSafe(normalized); const requested = Math.max(1, Math.min(4, Math.floor(count))); const urls = await localGenerate(process.env.BOBAI_LOCAL_IMAGE_PATH?.trim() || "/generate/image", { prompt: normalized, count: requested, inputImages: normalizeImages(inputImages) }); if (urls.length < requested) throw new Error(`local image provider returned ${urls.length} of ${requested} requested images`); return urls.slice(0, requested).map((url, index) => ({ url, prompt: normalized, index })); }
export async function generateVideo(prompt: string, inputImages?: string[]) { const normalized = prompt.trim(); if (!normalized) throw new Error("video prompt is required"); if (normalized.length > MAX_PROMPT_LENGTH) throw new Error("video prompt is too long"); assertMediaPromptSafe(normalized); const urls = await localGenerate(process.env.BOBAI_LOCAL_VIDEO_PATH?.trim() || "/generate/video", { prompt: normalized, inputImages: normalizeImages(inputImages) }); const url = urls[0]; if (!url) throw new Error("local video provider returned no media URL"); return { url, prompt: normalized }; }
