import { createHash } from "node:crypto";
import { assertMediaPromptSafe } from "./mediaSafety.js";
import { fluxGenerate } from "./flux.js";

type GeneratedImage = { url: string; prompt: string; index: number };
type MediaOptions = { prompt: string; count?: number; width?: number; height?: number; seed?: number };
const MAX_PROMPT_LENGTH = 8000;
const MAX_INPUT_IMAGES = 4;
function normalizeImages(inputImages: string[] | undefined) { if (!inputImages) return []; if (!Array.isArray(inputImages) || inputImages.length > MAX_INPUT_IMAGES) throw new Error("up to 4 input images are supported"); return inputImages.filter((image) => typeof image === "string" && image.trim()).slice(0, MAX_INPUT_IMAGES); }
function escapeXml(value: string) { return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"); }
function localSvg(prompt: string, index: number, options: MediaOptions) { const width=Math.max(256,Math.min(1536,Math.floor(options.width||1024))); const height=Math.max(256,Math.min(1536,Math.floor(options.height||1024))); const seed=options.seed??createHash("sha256").update(`${prompt}:${index}`).digest().readUInt32BE(0); const safePrompt=escapeXml(prompt.slice(0,180)); const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="#080b12"/><circle cx="${120+seed%(width-240)}" cy="${120+(seed>>>8)%(height-240)}" r="180" fill="white" opacity=".12"/><text x="50%" y="50%" fill="white" font-family="system-ui" font-size="32" text-anchor="middle">${safePrompt}</text></svg>`; return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`; }
export async function generateImages(prompt:string,count=4,inputImages?:string[]):Promise<GeneratedImage[]> { const normalized=prompt.trim(); if(!normalized)throw new Error("image prompt is required"); if(normalized.length>MAX_PROMPT_LENGTH)throw new Error("image prompt is too long"); assertMediaPromptSafe(normalized); normalizeImages(inputImages); const requested=Math.max(1,Math.min(4,Math.floor(count))); const local=await fluxGenerate(normalized,requested); if(local)return local; return Array.from({length:requested},(_,index)=>({url:localSvg(normalized,index,{prompt:normalized,count:requested}),prompt:normalized,index})); }
export async function generateVideo(prompt:string,inputImages?:string[]){const normalized=prompt.trim();if(!normalized)throw new Error("video prompt is required");if(normalized.length>MAX_PROMPT_LENGTH)throw new Error("video prompt is too long");assertMediaPromptSafe(normalized);normalizeImages(inputImages);throw new Error("local video generation requires a video model/runtime; BobAI does not fake video output");}
