import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from "node:crypto";
import { and, eq, gt, isNull, lt } from "drizzle-orm";
import { db, mfaChallenges, users } from "@bobai/db";
import { recordAudit } from "./audit.js";

const ISSUER = "BobAI";
const STEP_SECONDS = 30;
const CHALLENGE_TTL_MS = 5 * 60_000;
const MAX_CHALLENGE_ATTEMPTS = 5;

function encryptionKey() {
  const raw = process.env.BOBAI_MFA_ENCRYPTION_KEY?.trim();
  if (!raw) throw new Error("MFA encryption key is not configured");
  const key = /^[0-9a-f]{64}$/i.test(raw) ? Buffer.from(raw, "hex") : Buffer.from(raw, "base64");
  if (key.length !== 32) throw new Error("MFA encryption key must decode to 32 bytes");
  return key;
}
function encrypt(secret: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const ciphertext = Buffer.concat([cipher.update(secret, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${ciphertext.toString("base64url")}`; }
function decrypt(value: string) { const [ivText, tagText, ciphertextText] = value.split("."); if (!ivText || !tagText || !ciphertextText) throw new Error("invalid MFA secret"); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(ivText, "base64url")); decipher.setAuthTag(Buffer.from(tagText, "base64url")); return Buffer.concat([decipher.update(Buffer.from(ciphertextText, "base64url")), decipher.final()]).toString("utf8"); }
function base32Encode(value: Buffer) { const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; let bits = 0; let buffer = 0; let output = ""; for (const byte of value) { buffer = (buffer << 8) | byte; bits += 8; while (bits >= 5) { output += alphabet[(buffer >>> (bits - 5)) & 31]; bits -= 5; } } if (bits) output += alphabet[(buffer << (5 - bits)) & 31]; return output; }
function base32Decode(value: string) { const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; let bits = 0; let buffer = 0; const bytes: number[] = []; for (const char of value.replace(/=+$/g, "").toUpperCase()) { const index = alphabet.indexOf(char); if (index < 0) throw new Error("invalid base32 secret"); buffer = (buffer << 5) | index; bits += 5; if (bits >= 8) { bytes.push((buffer >>> (bits - 8)) & 255); bits -= 8; } } return Buffer.from(bytes); }
function hotp(secret: string, counter: number) { const key = base32Decode(secret); const counterBuffer = Buffer.alloc(8); counterBuffer.writeBigUInt64BE(BigInt(counter)); const digest = createHmac("sha1", key).update(counterBuffer).digest(); const offset = digest[digest.length - 1] & 15; const binary = ((digest[offset] & 127) << 24) | ((digest[offset + 1] & 255) << 16) | ((digest[offset + 2] & 255) << 8) | (digest[offset + 3] & 255); return String(binary % 1_000_000).padStart(6, "0"); }
export function verifyTotp(secret: string, code: string, now = Date.now()) { if (!/^\d{6}$/.test(code)) return false; const counter = Math.floor(now / 1000 / STEP_SECONDS); return [-1, 0, 1].some((offset) => hotp(secret, counter + offset) === code); }

export async function beginMfaSetup(userId: string) { const [user] = await db.select({ email: users.email, mfaEnabled: users.mfaEnabled }).from(users).where(and(eq(users.id, userId), isNull(users.deletedAt))).limit(1); if (!user) throw new Error("user not found"); if (user.mfaEnabled) throw new Error("MFA is already enabled"); const secret = base32Encode(randomBytes(20)); const label = encodeURIComponent(`${ISSUER}:${user.email}`); const issuer = encodeURIComponent(ISSUER); const otpauthUrl = `otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`; return { secret, otpauthUrl }; }
export async function enableMfa(userId: string, secret: string, code: string) { if (!/^[A-Z2-7]{16,64}$/.test(secret) || !verifyTotp(secret, code)) return false; const [user] = await db.update(users).set({ mfaEnabled: true, mfaSecretEncrypted: encrypt(secret), updatedAt: new Date() }).where(and(eq(users.id, userId), isNull(users.deletedAt))).returning({ id: users.id }); if (!user) return false; await recordAudit({ action: "mfa_enabled", resourceType: "user", resourceId: userId, userId }); return true; }
export async function disableMfa(userId: string, code: string) { const [user] = await db.select({ secret: users.mfaSecretEncrypted, enabled: users.mfaEnabled }).from(users).where(and(eq(users.id, userId), isNull(users.deletedAt))).limit(1); if (!user?.enabled || !user.secret || !verifyTotp(decrypt(user.secret), code)) return false; await db.update(users).set({ mfaEnabled: false, mfaSecretEncrypted: null, updatedAt: new Date() }).where(eq(users.id, userId)); await recordAudit({ action: "mfa_disabled", resourceType: "user", resourceId: userId, userId }); return true; }
export async function userMfaStatus(userId: string) { const [user] = await db.select({ enabled: users.mfaEnabled }).from(users).where(and(eq(users.id, userId), isNull(users.deletedAt))).limit(1); return Boolean(user?.enabled); }
export async function createMfaChallenge(userId: string) { const raw = randomBytes(32).toString("base64url"); await db.insert(mfaChallenges).values({ userId, tokenHash: createHash("sha256").update(raw).digest("hex"), expiresAt: new Date(Date.now() + CHALLENGE_TTL_MS) }); return raw; }
export async function verifyMfaChallenge(rawToken: string, code: string) { if (!/^[A-Za-z0-9_-]{40,64}$/.test(rawToken) || !/^\d{6}$/.test(code)) return null; const tokenHash = createHash("sha256").update(rawToken).digest("hex"); const now = new Date(); const [challenge] = await db.update(mfaChallenges).set({ attempts: mfaChallenges.attempts }).where(and(eq(mfaChallenges.tokenHash, tokenHash), gt(mfaChallenges.expiresAt, now), lt(mfaChallenges.attempts, MAX_CHALLENGE_ATTEMPTS))).returning({ id: mfaChallenges.id, userId: mfaChallenges.userId, attempts: mfaChallenges.attempts }); if (!challenge) return null; await db.update(mfaChallenges).set({ attempts: challenge.attempts + 1 }).where(eq(mfaChallenges.id, challenge.id)); const [user] = await db.select({ secret: users.mfaSecretEncrypted, enabled: users.mfaEnabled }).from(users).where(and(eq(users.id, challenge.userId), isNull(users.deletedAt))).limit(1); if (!user?.enabled || !user.secret) return null; if (!verifyTotp(decrypt(user.secret), code)) return null; await db.delete(mfaChallenges).where(eq(mfaChallenges.id, challenge.id)); return challenge.userId; }
export async function cleanupMfaChallenges() { await db.delete(mfaChallenges).where(lt(mfaChallenges.expiresAt, new Date())); }
setInterval(() => { cleanupMfaChallenges().catch(() => undefined); }, 60_000).unref();
