import { existsSync } from "node:fs";
import { spawn, type ChildProcess } from "node:child_process";
import { randomBytes } from "node:crypto";
const HOST="127.0.0.1";
const BASE_PORT=Math.min(65490,Math.max(1024,Number(process.env.BOBAI_PRODUCTION_MODEL_PORT||39850)));
const PYTHON=process.env.BOBAI_PYTHON||"python";
const CHECKPOINT=process.env.BOBAI_PRODUCTION_MODEL_CHECKPOINT||process.env.BOBAI_PRODUCTION_MODEL_PATH||"model-training/output/bob-production/latest.pt";
const TOKENIZER=process.env.BOBAI_PRODUCTION_MODEL_TOKENIZER||process.env.BOBAI_PRODUCTION_TOKENIZER_PATH||"model-training/output/bob-production/tokenizer.json";
const TIMEOUT_MS=Math.min(300000,Math.max(5000,Number(process.env.BOBAI_PRODUCTION_MODEL_TIMEOUT_MS||120000)));
const MAX_RESPONSE_BYTES=4*1024*1024;
type Worker={process:ChildProcess;token:string;port:number;ready:Promise<void>};
let workers:Worker[]=[];let nextWorker=0;
async function wait(child:ChildProcess,port:number){const end=Date.now()+TIMEOUT_MS;while(Date.now()<end){if(child.exitCode!==null)throw new Error("production model worker exited during startup");try{if((await fetch(`http://${HOST}:${port}/health`,{signal:AbortSignal.timeout(1000)})).ok)return}catch{}await new Promise(r=>setTimeout(r,200))}child.kill();throw new Error("production model worker startup timed out")}
export function productionModelConfigured(){return existsSync(CHECKPOINT)&&existsSync(TOKENIZER)}
async function startWorker(port:number):Promise<Worker>{const token=randomBytes(32).toString("base64url");const child=spawn(PYTHON,["model-training/production_model_server.py","--checkpoint",CHECKPOINT,"--tokenizer",TOKENIZER,"--host",HOST,"--port",String(port),"--token",token,"--device",process.env.BOBAI_PRODUCTION_MODEL_DEVICE||"auto"],{cwd:process.cwd(),stdio:["ignore","pipe","pipe"],windowsHide:true});child.stderr?.on("data",chunk=>{if(process.env.NODE_ENV!=="production")process.stderr.write(`[bob-production:${port}] ${chunk}`)});const ready=wait(child,port).catch(error=>{child.kill();workers=workers.filter(w=>w.process!==child);throw error});const worker={process:child,token,port,ready};child.once("exit",()=>{workers=workers.filter(w=>w.process!==child)});await ready;return worker}
export async function ensureProductionModel(){if(!productionModelConfigured())throw new Error(`BobAI production model files are missing (${CHECKPOINT}, ${TOKENIZER})`);if(workers.length)return workers;const requested=Number(process.env.BOBAI_PRODUCTION_MODEL_WORKERS||1);const count=Math.min(Math.max(Number.isFinite(requested)?Math.trunc(requested):1,1),8);for(let i=0;i<count;i++)workers.push(await startWorker(BASE_PORT+i));return workers}
function chooseWorker(pool:Worker[]){const worker=pool[nextWorker%pool.length];nextWorker=(nextWorker+1)%pool.length;return worker}
export async function productionModelInfer(messages:Array<{role:"system"|"user"|"assistant";content:string}>,options:{maxTokens?:number;temperature?:number;topK?:number}={}){const pool=await ensureProductionModel();const active=chooseWorker(pool);const body=JSON.stringify({messages,max_tokens:Math.min(Math.max(options.maxTokens??768,1),2048),temperature:Math.min(Math.max(options.temperature??.7,0),2),top_k:Math.min(Math.max(options.topK??50,1),512)});if(Buffer.byteLength(body)>4*1024*1024)throw new Error("production model request is too large");const response=await fetch(`http://${HOST}:${active.port}/infer`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${active.token}`},body,signal:AbortSignal.timeout(TIMEOUT_MS)});const length=Number(response.headers.get("content-length")||0);if(length>MAX_RESPONSE_BYTES)throw new Error("production model response is too large");const result=await response.json() as {content?:unknown;error?:unknown;model?:unknown};if(!response.ok||typeof result.error==="string")throw new Error(typeof result.error==="string"?result.error:`production model returned ${response.status}`);if(typeof result.content!=="string"||!result.content.trim())throw new Error("production model returned empty content");return{content:result.content,model:typeof result.model==="string"?result.model:"bob-production"}}
export async function productionModelStatus(){if(!productionModelConfigured())return{ready:false,modelId:"bob-production",checkpoint:CHECKPOINT,tokenizer:TOKENIZER,error:"production model files are missing"};try{const pool=await ensureProductionModel();const statuses=await Promise.all(pool.map(async w=>{const response=await fetch(`http://${HOST}:${w.port}/health`,{signal:AbortSignal.timeout(2000)});return{...(await response.json() as object),ready:response.ok,port:w.port,pid:w.process.pid}}));return{ready:statuses.every(s=>s.ready),modelId:"bob-production",checkpoint:CHECKPOINT,tokenizer:TOKENIZER,workers:statuses}}catch(error){return{ready:false,modelId:"bob-production",checkpoint:CHECKPOINT,tokenizer:TOKENIZER,error:error instanceof Error?error.message:"production model unavailable"}}}
export async function stopProductionModel(){const active=workers.splice(0);for(const worker of active)worker.process.kill()}
process.once("SIGTERM",()=>{void stopProductionModel()});process.once("SIGINT",()=>{void stopProductionModel()});
