import { and, eq, lte, sql } from "drizzle-orm";
import { db, researchBriefs, researchSessions } from "@bobai/db";
import { randomUUID } from "node:crypto";
import { webSearch } from "./research.js";
import { consumeResearchQuota } from "./researchQuota.js";
const MIN_INTERVAL = 60 * 60_000; const MAX_INTERVAL = 30 * 24 * 60 * 60_000;
export function normalizeBriefInterval(value: unknown) { const interval = Number(value); if (!Number.isFinite(interval) || interval < MIN_INTERVAL || interval > MAX_INTERVAL) throw new Error("brief interval must be between 1 hour and 30 days"); return Math.floor(interval); }
export async function createResearchBrief(input: { workspaceId: string; userId: string; name: string; query: string; options?: Record<string, unknown>; intervalMs: number }) { if (!input.name.trim() || input.name.length > 200) throw new Error("invalid brief name"); if (!input.query.trim() || input.query.length > 2_000) throw new Error("invalid brief query"); const intervalMs = normalizeBriefInterval(input.intervalMs); const nextRunAt = new Date(Date.now() + intervalMs); return db.insert(researchBriefs).values({ id: randomUUID(), workspaceId: input.workspaceId, userId: input.userId, name: input.name.trim(), query: input.query.trim(), options: input.options, intervalMs, nextRunAt, enabled: true }).returning(); }
export async function listResearchBriefs(workspaceId: string, userId: string) { return db.select().from(researchBriefs).where(and(eq(researchBriefs.workspaceId, workspaceId), eq(researchBriefs.userId, userId))).orderBy(researchBriefs.createdAt); }
export async function deleteResearchBrief(id: string, workspaceId: string, userId: string) { const result = await db.delete(researchBriefs).where(and(eq(researchBriefs.id, id), eq(researchBriefs.workspaceId, workspaceId), eq(researchBriefs.userId, userId))).returning({ id: researchBriefs.id }); return Boolean(result[0]); }
export async function runDueResearchBriefs() { const due = await db.select({ id: researchBriefs.id }).from(researchBriefs).where(and(eq(researchBriefs.enabled, true), lte(researchBriefs.nextRunAt, new Date()))).limit(20); for (const candidate of due) { const claimedAt = new Date(); const claimed = await db.update(researchBriefs).set({ nextRunAt: sql`now() + (${researchBriefs.intervalMs} * interval '1 millisecond')`, updatedAt: claimedAt }).where(and(eq(researchBriefs.id, candidate.id), eq(researchBriefs.enabled, true), lte(researchBriefs.nextRunAt, claimedAt))).returning(); const brief = claimed[0]; if (!brief) continue; try { const result = await webSearch(brief.query, (brief.options && typeof brief.options === "object" && !Array.isArray(brief.options)) ? brief.options as Record<string, unknown> : {}); await consumeResearchQuota(brief.userId, result.sources.length); const sessionId = randomUUID(); await db.insert(researchSessions).values({ id: sessionId, workspaceId: brief.workspaceId, userId: brief.userId, query: result.query, sources: result.sources, status: "scheduled" }); const now = new Date(); await db.update(researchBriefs).set({ lastRunAt: now, lastSessionId: sessionId, nextRunAt: new Date(now.getTime() + brief.intervalMs), updatedAt: now }).where(eq(researchBriefs.id, brief.id)); } catch { const now = new Date(); await db.update(researchBriefs).set({ nextRunAt: new Date(now.getTime() + Math.min(brief.intervalMs, 6 * 60 * 60_000)), updatedAt: now }).where(eq(researchBriefs.id, brief.id)); } } }
