import { createCipheriv, createDecipheriv, createHash, createPublicKey, createSign, createVerify, randomBytes } from "node:crypto";
import { and, eq, gt, isNull } from "drizzle-orm";
import { db, authIdentities, authOAuthStates, users } from "@bobai/db";
import { issueSession } from "./auth.js";
import { createMfaChallenge } from "./mfa.js";
import { recordAudit } from "./audit.js";
export type SocialProvider = "google" | "github" | "apple";
type Profile = { subject: string; email: string; emailVerified: boolean; displayName?: string; avatarUrl?: string };
type ProviderClientConfig = { clientId: string; clientSecret?: string; teamId?: string; keyId?: string; privateKey?: string };
const STATE_TTL_MS = 10 * 60_000;
const key = () => { const raw = process.env.BOBAI_MFA_ENCRYPTION_KEY?.trim(); if (!raw) throw new Error("MFA encryption key is not configured"); const value = /^[0-9a-f]{64}$/i.test(raw) ? Buffer.from(raw, "hex") : Buffer.from(raw, "base64"); if (value.length !== 32) throw new Error("MFA encryption key must decode to 32 bytes"); return value; };
const encrypt = (value: string) => { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key(), iv); const body = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${body.toString("base64url")}`; };
const decrypt = (value: string) => { const [iv, tag, body] = value.split("."); if (!iv || !tag || !body) throw new Error("invalid OAuth secret"); const decipher = createDecipheriv("aes-256-gcm", key(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(body, "base64url")), decipher.final()]).toString("utf8"); };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const base64url = (value: Buffer) => value.toString("base64url");
const redirectBase = () => (process.env.BOBAI_AUTH_REDIRECT_BASE_URL?.trim() || `http://localhost:${process.env.PORT || "3001"}`).replace(/\/$/, "");
const callbackUrl = (provider: SocialProvider) => `${redirectBase()}/auth/oauth/${provider}/callback`;
const verifier = () => base64url(randomBytes(32));
const challenge = (value: string) => base64url(createHash("sha256").update(value).digest());
const nonce = () => base64url(randomBytes(32));
function config(provider: "google"): Required<Pick<ProviderClientConfig, "clientId" | "clientSecret">>;
function config(provider: "github"): Required<Pick<ProviderClientConfig, "clientId" | "clientSecret">>;
function config(provider: "apple"): Required<Pick<ProviderClientConfig, "clientId" | "teamId" | "keyId" | "privateKey">>;
function config(provider: SocialProvider): ProviderClientConfig;
function config(provider: SocialProvider): ProviderClientConfig { if (provider === "google") { const clientId = process.env.BOBAI_GOOGLE_CLIENT_ID?.trim(); const clientSecret = process.env.BOBAI_GOOGLE_CLIENT_SECRET?.trim(); if (!clientId || !clientSecret) throw new Error("Google sign-in is not configured"); return { clientId, clientSecret }; } if (provider === "github") { const clientId = process.env.BOBAI_GITHUB_CLIENT_ID?.trim(); const clientSecret = process.env.BOBAI_GITHUB_CLIENT_SECRET?.trim(); if (!clientId || !clientSecret) throw new Error("GitHub sign-in is not configured"); return { clientId, clientSecret }; } const clientId = process.env.BOBAI_APPLE_CLIENT_ID?.trim(); const teamId = process.env.BOBAI_APPLE_TEAM_ID?.trim(); const keyId = process.env.BOBAI_APPLE_KEY_ID?.trim(); const privateKey = process.env.BOBAI_APPLE_PRIVATE_KEY?.replace(/\\n/g, "\n").trim(); if (!clientId || !teamId || !keyId || !privateKey) throw new Error("Apple sign-in is not configured"); return { clientId, teamId, keyId, privateKey }; }
function appleClientSecret(c: Required<Pick<ProviderClientConfig, "clientId" | "teamId" | "keyId" | "privateKey">>) { const now = Math.floor(Date.now() / 1000); const header = base64url(Buffer.from(JSON.stringify({ alg: "ES256", kid: c.keyId, typ: "JWT" }))); const payload = base64url(Buffer.from(JSON.stringify({ iss: c.teamId, iat: now, exp: now + 300, aud: "https://appleid.apple.com", sub: c.clientId }))); const unsigned = `${header}.${payload}`; const signer = createSign("SHA256"); signer.update(unsigned); signer.end(); const signature = signer.sign({ key: c.privateKey, dsaEncoding: "ieee-p1363" }); return `${unsigned}.${base64url(signature)}`; }
async function jsonFetch(url: string, init: RequestInit, maxBytes = 256_000) { const response = await fetch(url, init); const text = await response.text(); if (Buffer.byteLength(text, "utf8") > maxBytes) throw new Error("OAuth provider response too large"); let data: unknown = {}; try { data = JSON.parse(text); } catch { throw new Error("invalid OAuth provider response"); } if (!response.ok) throw new Error("OAuth provider request failed"); return data as Record<string, unknown>; }
const formBody = (values: Record<string, string>) => new URLSearchParams(values).toString();
export async function beginSocialLogin(provider: SocialProvider) { const c = config(provider); const state = randomBytes(32).toString("base64url"); const codeVerifier = verifier(); const requestNonce = nonce(); const redirectUri = callbackUrl(provider); await db.insert(authOAuthStates).values({ provider, stateHash: hash(state), codeVerifierEncrypted: encrypt(codeVerifier), nonceHash: hash(requestNonce), redirectUri, expiresAt: new Date(Date.now() + STATE_TTL_MS) }); const url = new URL(provider === "google" ? "https://accounts.google.com/o/oauth2/v2/auth" : provider === "github" ? "https://github.com/login/oauth/authorize" : "https://appleid.apple.com/auth/authorize"); url.searchParams.set("client_id", c.clientId); url.searchParams.set("redirect_uri", redirectUri); url.searchParams.set("response_type", "code"); url.searchParams.set("state", state); url.searchParams.set("code_challenge", challenge(codeVerifier)); url.searchParams.set("code_challenge_method", "S256"); if (provider === "google") { url.searchParams.set("scope", "openid email profile"); url.searchParams.set("access_type", "online"); } if (provider === "github") url.searchParams.set("scope", "read:user user:email"); if (provider === "apple") { url.searchParams.set("scope", "name email"); url.searchParams.set("response_mode", "form_post"); url.searchParams.set("nonce", requestNonce); } return url.toString(); }
async function consumeState(provider: SocialProvider, rawState: string) { if (!/^[A-Za-z0-9_-]{40,64}$/.test(rawState)) return null; const now = new Date(); const [state] = await db.update(authOAuthStates).set({ consumedAt: now }).where(and(eq(authOAuthStates.provider, provider), eq(authOAuthStates.stateHash, hash(rawState)), isNull(authOAuthStates.consumedAt), gt(authOAuthStates.expiresAt, now))).returning({ id: authOAuthStates.id, codeVerifierEncrypted: authOAuthStates.codeVerifierEncrypted, nonceHash: authOAuthStates.nonceHash, redirectUri: authOAuthStates.redirectUri }); return state ? { codeVerifier: decrypt(state.codeVerifierEncrypted), nonceHash: state.nonceHash, redirectUri: state.redirectUri } : null; }
async function googleProfile(code: string, verifierValue: string, redirectUri: string): Promise<Profile> { const c = config("google"); const token = await jsonFetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: formBody({ code, client_id: c.clientId, client_secret: c.clientSecret, redirect_uri: redirectUri, grant_type: "authorization_code", code_verifier: verifierValue }) }); const access = typeof token.access_token === "string" ? token.access_token : ""; if (!access) throw new Error("Google authorization failed"); const profile = await jsonFetch("https://openidconnect.googleapis.com/v1/userinfo", { headers: { Authorization: `Bearer ${access}` } }); if (typeof profile.sub !== "string" || typeof profile.email !== "string" || profile.email_verified !== true) throw new Error("Google account email is not verified"); return { subject: profile.sub, email: profile.email.trim().toLowerCase(), emailVerified: true, displayName: typeof profile.name === "string" ? profile.name : undefined, avatarUrl: typeof profile.picture === "string" ? profile.picture : undefined }; }
async function githubProfile(code: string, verifierValue: string, redirectUri: string): Promise<Profile> { const c = config("github"); const token = await jsonFetch("https://github.com/login/oauth/access_token", { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" }, body: formBody({ code, client_id: c.clientId, client_secret: c.clientSecret, redirect_uri: redirectUri, code_verifier: verifierValue }) }); const access = typeof token.access_token === "string" ? token.access_token : ""; if (!access) throw new Error("GitHub authorization failed"); const headers = { Authorization: `Bearer ${access}`, Accept: "application/vnd.github+json", "User-Agent": "BobAI" }; const profile = await jsonFetch("https://api.github.com/user", { headers }); const emails = await jsonFetch("https://api.github.com/user/emails", { headers }); const emailList: unknown[] = Array.isArray(emails) ? emails : []; const verified = emailList.find((item) => item && typeof item === "object" && (item as { verified?: unknown }).verified === true && typeof (item as { email?: unknown }).email === "string") as { email: string } | undefined; if (typeof profile.id !== "number" || !verified) throw new Error("GitHub account email is not verified"); return { subject: String(profile.id), email: verified.email.trim().toLowerCase(), emailVerified: true, displayName: typeof profile.name === "string" && profile.name.trim() ? profile.name : typeof profile.login === "string" ? profile.login : undefined, avatarUrl: typeof profile.avatar_url === "string" ? profile.avatar_url : undefined }; }
function decodeJwtPayload(token: string) { const parts = token.split("."); if (parts.length !== 3) throw new Error("invalid Apple identity token"); return JSON.parse(Buffer.from(parts[1], "base64url").toString("utf8")) as Record<string, unknown>; }
function rawEcdsaToDer(raw: Buffer) { if (raw.length !== 64) throw new Error("invalid Apple signature"); const normalize = (part: Buffer) => { let value = Buffer.from(part); while (value.length > 1 && value[0] === 0) value = value.subarray(1); if (value[0] & 0x80) value = Buffer.concat([Buffer.from([0]), value]); return Buffer.concat([Buffer.from([0x02, value.length]), value]); }; const r = normalize(raw.subarray(0, 32)); const s = normalize(raw.subarray(32, 64)); const body = Buffer.concat([r, s]); if (body.length >= 128) throw new Error("invalid Apple signature"); return Buffer.concat([Buffer.from([0x30, body.length]), body]); }
async function verifyAppleJwt(token: string, clientId: string, nonceHash: string) { const parts = token.split("."); if (parts.length !== 3) throw new Error("invalid Apple identity token"); const header = JSON.parse(Buffer.from(parts[0], "base64url").toString("utf8")) as { kid?: string; alg?: string }; const payload = decodeJwtPayload(token); if (header.alg !== "ES256" || typeof header.kid !== "string") throw new Error("invalid Apple identity token"); const keys = await jsonFetch("https://appleid.apple.com/auth/keys", { headers: { Accept: "application/json" } }); const keySet = Array.isArray(keys.keys) ? keys.keys : []; const jwk = keySet.find((item) => item && typeof item === "object" && (item as { kid?: unknown }).kid === header.kid) as { kty?: string; crv?: string; x?: string; y?: string } | undefined; if (!jwk?.x || !jwk.y || jwk.kty !== "EC" || jwk.crv !== "P-256") throw new Error("Apple signing key unavailable"); const publicKey = createPublicKey({ key: { kty: jwk.kty, crv: jwk.crv, x: jwk.x, y: jwk.y }, format: "jwk" }); const signature = Buffer.from(parts[2], "base64url"); const verifierObject = createVerify("SHA256"); verifierObject.update(`${parts[0]}.${parts[1]}`); verifierObject.end(); if (!verifierObject.verify(publicKey, rawEcdsaToDer(signature))) throw new Error("invalid Apple identity signature"); if (payload.iss !== "https://appleid.apple.com" || payload.aud !== clientId || typeof payload.exp !== "number" || payload.exp <= Math.floor(Date.now() / 1000) || typeof payload.nonce !== "string" || hash(payload.nonce) !== nonceHash) throw new Error("invalid Apple identity claims"); return payload; }
async function appleProfile(code: string, verifierValue: string, redirectUri: string, nonceHash: string): Promise<Profile> { const c = config("apple"); const token = await jsonFetch("https://appleid.apple.com/auth/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: formBody({ client_id: c.clientId, client_secret: appleClientSecret(c), code, grant_type: "authorization_code", redirect_uri: redirectUri, code_verifier: verifierValue }) }); const idToken = typeof token.id_token === "string" ? token.id_token : ""; if (!idToken) throw new Error("Apple authorization failed"); const payload = await verifyAppleJwt(idToken, c.clientId, nonceHash); if (typeof payload.sub !== "string" || typeof payload.email !== "string") throw new Error("Apple account email is unavailable"); return { subject: payload.sub, email: payload.email.trim().toLowerCase(), emailVerified: payload.email_verified === true, displayName: undefined }; }
async function profileFor(provider: SocialProvider, code: string, verifierValue: string, redirectUri: string, nonceHash: string) { if (provider === "google") return googleProfile(code, verifierValue, redirectUri); if (provider === "github") return githubProfile(code, verifierValue, redirectUri); return appleProfile(code, verifierValue, redirectUri, nonceHash); }
export async function completeSocialLogin(provider: SocialProvider, code: string, rawState: string, metadata?: Record<string, unknown>) { const state = await consumeState(provider, rawState); if (!state || !code || code.length > 2048) throw new Error("invalid or expired social login state"); const profile = await profileFor(provider, code, state.codeVerifier, state.redirectUri, state.nonceHash); if (!profile.emailVerified) throw new Error("social account email is not verified"); const [identity] = await db.select({ userId: authIdentities.userId }).from(authIdentities).where(and(eq(authIdentities.provider, provider), eq(authIdentities.providerSubject, profile.subject))).limit(1); let userId = identity?.userId; if (!userId) { const [user] = await db.select({ id: users.id }).from(users).where(and(eq(users.email, profile.email), isNull(users.deletedAt))).limit(1); if (!user) { const error = new Error("social account is not linked to a BobAI account"); (error as Error & { code?: string }).code = "SOCIAL_ACCOUNT_NOT_LINKED"; throw error; } userId = user.id; try { await db.insert(authIdentities).values({ userId, provider, providerSubject: profile.subject, email: profile.email }); } catch { const [existing] = await db.select({ userId: authIdentities.userId }).from(authIdentities).where(and(eq(authIdentities.provider, provider), eq(authIdentities.providerSubject, profile.subject))).limit(1); if (existing?.userId) userId = existing.userId; else throw new Error("social identity could not be linked"); } await db.update(users).set({ emailVerifiedAt: new Date(), ...(profile.displayName ? { displayName: profile.displayName } : {}), ...(profile.avatarUrl ? { avatarUrl: profile.avatarUrl } : {}), updatedAt: new Date() }).where(eq(users.id, userId)); } const [current] = await db.select({ id: users.id, deletedAt: users.deletedAt, mfaEnabled: users.mfaEnabled, mfaSecretEncrypted: users.mfaSecretEncrypted, emailVerifiedAt: users.emailVerifiedAt }).from(users).where(eq(users.id, userId)).limit(1); if (!current || current.deletedAt || !current.emailVerifiedAt) throw new Error("account unavailable"); if (current.mfaEnabled && current.mfaSecretEncrypted) { const challengeToken = await createMfaChallenge(userId); return { mfaRequired: true as const, challengeToken }; } const session = await issueSession(userId, metadata); await recordAudit({ action: "social_login_succeeded", resourceType: "session", resourceId: session.sessionId, userId, sessionId: session.sessionId, metadata: { provider } }); return session; }
export const socialProviders = ["google", "apple", "github"] as const;
