import { eq } from "drizzle-orm";
import { db, users } from "@bobai/db";
import { Router, type Request, type Response } from "express";
import { completeMfaLogin, createUser, login, loginWithEmailOtp, refresh, revoke } from "../services/auth.js";
import { completeSocialLogin, beginSocialLogin, socialProviders, type SocialProvider } from "../services/socialAuth.js";
import { requestEmailOtp, verifyEmailOtp } from "../services/otp.js";
import { resetPassword, requestPasswordReset } from "../services/passwordReset.js";
import { sendPasswordResetEmail } from "../services/email.js";
import { requireAuth } from "../middleware/auth.js";
import { authAbuseKey, checkAuthAbuse, clearAuthFailures, recordAuthFailure } from "../services/authAbuse.js";

const router = Router();
const email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const username = /^[A-Za-z0-9_]{3,32}$/;
const authBuckets = new Map<string, { startedAt: number; count: number }>();
const AUTH_WINDOW_MS = 15 * 60_000;
const AUTH_MAX_ATTEMPTS = 10;
const MAX_AUTH_BUCKETS = 10_000;
const REFRESH_COOKIE = "bobai_refresh";
const ACCESS_COOKIE = "bobai_access";
function pruneAuthBuckets(now = Date.now()) { const cutoff = now - AUTH_WINDOW_MS; for (const [key, bucket] of authBuckets) if (bucket.startedAt < cutoff) authBuckets.delete(key); }
function limited(req: { ip?: string }, key: string) { const now = Date.now(); const bucketKey = `${req.ip || "unknown"}:${key}`; const current = authBuckets.get(bucketKey); if (!current || now - current.startedAt >= AUTH_WINDOW_MS) { if (authBuckets.size >= MAX_AUTH_BUCKETS) pruneAuthBuckets(now); if (authBuckets.size >= MAX_AUTH_BUCKETS) return true; authBuckets.set(bucketKey, { startedAt: now, count: 1 }); return false; } current.count += 1; return current.count > AUTH_MAX_ATTEMPTS; }
setInterval(() => pruneAuthBuckets(), AUTH_WINDOW_MS).unref();
function cookieOptions(maxAge: number) { return { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "strict" as const, path: "/", maxAge }; }
function readCookie(req: { header(name: string): string | undefined }, name: string) { const header = req.header("cookie") || ""; const item = header.split(";").map((part) => part.trim()).find((part) => part.startsWith(`${name}=`)); if (!item) return ""; try { return decodeURIComponent(item.slice(name.length + 1)); } catch { return ""; } }
function setSessionCookies(res: { cookie(name: string, value: string, options: object): void }, session: { accessToken: string; refreshToken: string }) { res.cookie(ACCESS_COOKIE, session.accessToken, cookieOptions(15 * 60 * 1000)); res.cookie(REFRESH_COOKIE, session.refreshToken, cookieOptions(30 * 24 * 60 * 60 * 1000)); }
function clearSessionCookies(res: { clearCookie(name: string, options?: object): void }) { const options = { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "strict" as const, path: "/" }; res.clearCookie(ACCESS_COOKIE, options); res.clearCookie(REFRESH_COOKIE, options); }

router.post("/register", async (req, res) => { const { email: address, username: name, password, termsAccepted, termsVersion } = req.body ?? {}; const normalizedEmail = typeof address === "string" ? address.trim().toLowerCase() : ""; const normalizedUsername = typeof name === "string" ? name.trim() : ""; const requiredTermsVersion = process.env.BOBAI_TERMS_VERSION; if (!email.test(normalizedEmail) || !username.test(normalizedUsername) || typeof password !== "string" || password.length < 6 || password.length > 128) return res.status(400).json({ error: "invalid registration details" }); if (termsAccepted !== true || typeof termsVersion !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(termsVersion) || (requiredTermsVersion && termsVersion !== requiredTermsVersion)) return res.status(400).json({ error: "acceptance of the current Terms of Service is required" }); if (limited(req, "register")) return res.status(429).json({ error: "too many registration attempts", retryAfterSeconds: 900 }); try { const user = await createUser(normalizedEmail, normalizedUsername, password, { termsAccepted: true, termsVersion }); try { await requestEmailOtp(normalizedEmail); } catch { /* verification can be requested again */ } return res.status(201).json({ requiresVerification: true, user }); } catch (error) { const databaseError = error as { code?: string }; if (databaseError.code === "PASSWORD_POLICY") return res.status(400).json({ error: error instanceof Error ? error.message : "password does not meet security requirements" }); if (databaseError.code === "TERMS_REQUIRED") return res.status(400).json({ error: "acceptance of the current Terms of Service is required" }); if (databaseError.code === "ACCOUNT_EXISTS") return res.status(409).json({ error: "email or username is already in use" }); if (databaseError.code === "23505" || (error && typeof error === "object" && "cause" in error && (error as { cause?: { code?: string } }).cause?.code === "23505")) return res.status(409).json({ error: "email or username is already in use" }); if (process.env.NODE_ENV !== "production") console.error("[AUTH] registration failed", error); return res.status(503).json({ error: "account service unavailable" }); } });
router.post("/login", async (req, res) => { const { email: address, password } = req.body ?? {}; const normalizedEmail = typeof address === "string" ? address.trim().toLowerCase() : ""; if (typeof address !== "string" || typeof password !== "string") return res.status(400).json({ error: "invalid credentials" }); if (limited(req, `login:${normalizedEmail.slice(0, 254)}`)) return res.status(429).json({ error: "too many login attempts", retryAfterSeconds: 900 }); const abuseKey = authAbuseKey(req.ip, normalizedEmail); const abuse = checkAuthAbuse(abuseKey); if (abuse.blocked) return res.status(429).json({ error: "login temporarily blocked", retryAfterSeconds: abuse.retryAfterSeconds }); try { const result = await login(normalizedEmail, password, { userAgent: req.get("user-agent") }); if (!result) { const retryAfterSeconds = recordAuthFailure(abuseKey); return res.status(401).json({ error: "invalid email or password", ...(retryAfterSeconds ? { retryAfterSeconds } : {}) }); } if ("mfaRequired" in result) return res.status(200).json({ mfaRequired: true, challengeToken: result.challengeToken, expiresInSeconds: 300 }); clearAuthFailures(abuseKey); setSessionCookies(res, result); return res.json({ expiresIn: result.expiresIn }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] login failed", error); return res.status(503).json({ error: "authentication service unavailable" }); } });
router.post("/login-otp/request", async (req, res) => { const address = typeof req.body?.email === "string" ? req.body.email.trim().toLowerCase() : ""; if (!email.test(address)) return res.status(400).json({ error: "invalid email" }); if (limited(req, `login-otp-request:${address.slice(0, 254)}`)) return res.status(429).json({ error: "too many code requests", retryAfterSeconds: 900 }); try { await requestEmailOtp(address, "login"); return res.status(202).json({ message: "if the account exists, a sign-in code has been sent" }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] login OTP delivery failed", error); return res.status(503).json({ error: "sign-in code could not be sent right now" }); } });
router.post("/login-otp/verify", async (req, res) => { const address = typeof req.body?.email === "string" ? req.body.email.trim().toLowerCase() : ""; const code = typeof req.body?.code === "string" ? req.body.code : ""; if (!email.test(address) || !/^\d{6}$/.test(code)) return res.status(400).json({ error: "invalid sign-in code" }); if (limited(req, `login-otp-verify:${address.slice(0, 254)}`)) return res.status(429).json({ error: "too many code attempts", retryAfterSeconds: 900 }); try { const verified = await verifyEmailOtp(address, code, "login"); if (!verified) return res.status(401).json({ error: "invalid or expired sign-in code" }); const [user] = await db.select({ id: users.id }).from(users).where(eq(users.email, address)).limit(1); if (!user) return res.status(401).json({ error: "invalid or expired sign-in code" }); const result = await loginWithEmailOtp(user.id, { userAgent: req.get("user-agent") }); if (!result) return res.status(401).json({ error: "account is unavailable" }); if ("mfaRequired" in result) return res.status(200).json({ mfaRequired: true, challengeToken: result.challengeToken, expiresInSeconds: 300 }); setSessionCookies(res, result); return res.json({ expiresIn: result.expiresIn }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] login OTP verification failed", error); return res.status(503).json({ error: "sign-in code verification is unavailable" }); } });
router.post("/mfa/verify", async (req, res) => { const challengeToken = typeof req.body?.challengeToken === "string" ? req.body.challengeToken : ""; const code = typeof req.body?.code === "string" ? req.body.code : ""; const abuseKey = authAbuseKey(req.ip, challengeToken.slice(0, 64)); const abuse = checkAuthAbuse(abuseKey); if (abuse.blocked) return res.status(429).json({ error: "MFA verification temporarily blocked", retryAfterSeconds: abuse.retryAfterSeconds }); if (limited(req, "mfa-verify") || !/^\d{6}$/.test(code)) { recordAuthFailure(abuseKey); return res.status(429).json({ error: "invalid or too many MFA attempts" }); } try { const session = await completeMfaLogin(challengeToken, code, { userAgent: req.get("user-agent") }); if (!session) { recordAuthFailure(abuseKey); return res.status(401).json({ error: "invalid or expired MFA challenge" }); } clearAuthFailures(abuseKey); setSessionCookies(res, session); return res.json({ expiresIn: session.expiresIn }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] MFA verification failed", error); return res.status(503).json({ error: "MFA verification unavailable" }); } });
router.get("/oauth/:provider/start", async (req, res) => { const provider = typeof req.params.provider === "string" ? req.params.provider as SocialProvider : "google"; if (!(socialProviders as readonly string[]).includes(provider)) return res.status(404).json({ error: "unsupported sign-in provider" }); try { return res.redirect(await beginSocialLogin(provider)); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] social login start failed", error); return res.status(503).json({ error: error instanceof Error ? error.message : "social sign-in is unavailable" }); } });
async function handleSocialCallback(req: Request, res: Response) { const provider = typeof req.params.provider === "string" ? req.params.provider as SocialProvider : "google"; const code = typeof req.body?.code === "string" ? req.body.code : typeof req.query.code === "string" ? req.query.code : ""; const state = typeof req.body?.state === "string" ? req.body.state : typeof req.query.state === "string" ? req.query.state : ""; const providerError = typeof req.body?.error === "string" ? req.body.error : typeof req.query.error === "string" ? req.query.error : ""; const web = process.env.BOBAI_WEB_URL?.trim() || "http://localhost:3000"; const destination = new URL("/login", web); if (!(socialProviders as readonly string[]).includes(provider)) return res.status(404).send("unsupported sign-in provider"); if (providerError || !code || !state) { destination.searchParams.set("oauth_error", "sign-in was cancelled or could not be completed"); return res.redirect(destination.toString()); } try { const result = await completeSocialLogin(provider, code, state, { userAgent: req.get("user-agent") }); if ("mfaRequired" in result) { destination.searchParams.set("mfa", result.challengeToken); destination.searchParams.set("oauth", "1"); return res.redirect(destination.toString()); } setSessionCookies(res, result); return res.redirect(new URL("/onboarding", web).toString()); } catch (failure) { const message = failure instanceof Error && failure.message === "social account is not linked to a BobAI account" ? "this social account is not linked to a BobAI account yet" : "social sign-in could not be completed"; destination.searchParams.set("oauth_error", message); return res.redirect(destination.toString()); } }
router.get("/oauth/:provider/callback", handleSocialCallback);
router.post("/oauth/:provider/callback", handleSocialCallback);
router.post("/refresh", async (req, res) => { const refreshToken = readCookie(req, REFRESH_COOKIE); if (!refreshToken) return res.status(401).json({ error: "refresh token required" }); const session = await refresh(refreshToken); if (!session) { clearSessionCookies(res); return res.status(401).json({ error: "invalid or expired session" }); } setSessionCookies(res, session); return res.json({ expiresIn: session.expiresIn }); });
router.post("/logout", async (req, res) => { const refreshToken = readCookie(req, REFRESH_COOKIE); if (refreshToken) await revoke(refreshToken); clearSessionCookies(res); return res.status(204).send(); });
router.post("/otp/request", async (req, res) => { const address = typeof req.body?.email === "string" ? req.body.email.trim().toLowerCase() : ""; if (!email.test(address)) return res.status(400).json({ error: "invalid email" }); if (limited(req, `otp-request:${address.slice(0, 254)}`)) return res.status(429).json({ error: "too many verification requests", retryAfterSeconds: 900 }); try { await requestEmailOtp(address); return res.status(202).json({ message: "if the account exists, a verification code has been sent" }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] otp delivery failed", error); return res.status(503).json({ error: "verification email could not be sent right now" }); } });
router.post("/otp/verify", async (req, res) => { const address = typeof req.body?.email === "string" ? req.body.email.trim().toLowerCase() : ""; const code = typeof req.body?.code === "string" ? req.body.code : ""; if (!email.test(address) || !/^\d{6}$/.test(code)) return res.status(400).json({ error: "invalid verification code" }); if (limited(req, `otp-verify:${address.slice(0, 254)}`)) return res.status(429).json({ error: "too many verification attempts", retryAfterSeconds: 900 }); try { if (!await verifyEmailOtp(address, code)) return res.status(400).json({ error: "invalid or expired verification code" }); return res.json({ verified: true }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] otp verification failed", error); return res.status(503).json({ error: "verification unavailable" }); } });
router.post("/password-reset/request", async (req, res) => { const address = typeof req.body?.email === "string" ? req.body.email.trim().toLowerCase() : ""; if (!email.test(address)) return res.status(400).json({ error: "invalid email" }); if (limited(req, `password-reset:${address.slice(0, 254)}`)) return res.status(429).json({ error: "too many password reset attempts", retryAfterSeconds: 900 }); try { const reset = await requestPasswordReset(address); if (reset) { try { await sendPasswordResetEmail(reset.email, reset.token); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] password reset email failed", error); } } return res.status(202).json({ message: "if the account exists, a password reset link has been sent" }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] password reset request failed", error); return res.status(503).json({ error: "password reset is temporarily unavailable" }); } });
router.post("/password-reset/confirm", async (req, res) => { const resetToken = typeof req.body?.token === "string" ? req.body.token : ""; const password = typeof req.body?.password === "string" ? req.body.password : ""; if (!resetToken || !password) return res.status(400).json({ error: "reset token and password are required" }); if (limited(req, "password-reset-confirm")) return res.status(429).json({ error: "too many password reset attempts", retryAfterSeconds: 900 }); try { const result = await resetPassword(resetToken, password); if (!result.ok) return res.status(400).json({ error: result.error }); return res.json({ reset: true }); } catch (error) { if (process.env.NODE_ENV !== "production") console.error("[AUTH] password reset failed", error); return res.status(503).json({ error: "password reset is temporarily unavailable" }); } });
router.get("/status", requireAuth, (req, res) => res.json({ userId: req.user!.id }));
export default router;
