import { Router } from "express";
import { createHash, randomBytes } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
import { db, fileShares, uploads, users, workspaceInvitations, workspaceMembers, workspaces } from "@bobai/db";
import { requireAuth } from "../middleware/auth.js";
import { recordAudit } from "../services/audit.js";

const router = Router();
const ROLES = new Set(["owner", "admin", "member", "viewer"]);
const PERMISSIONS = new Set(["read", "write"]);
const INVITE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function normalizeEmail(value: unknown) { return typeof value === "string" ? value.trim().toLowerCase().slice(0, 320) : ""; }
function roleRank(role: string) { return role === "owner" ? 4 : role === "admin" ? 3 : role === "member" ? 2 : 1; }
async function membership(userId: string, workspaceId: string) { const [row] = await db.select({ id: workspaceMembers.id, role: workspaceMembers.role, permissions: workspaceMembers.permissions }).from(workspaceMembers).where(and(eq(workspaceMembers.userId, userId), eq(workspaceMembers.workspaceId, workspaceId))).limit(1); return row ?? null; }
async function manageWorkspace(userId: string, workspaceId: string) { const member = await membership(userId, workspaceId); return member && roleRank(member.role) >= 3 ? member : null; }
router.use(requireAuth);
router.get("/workspaces", async (req, res) => { const rows = await db.select({ id: workspaces.id, name: workspaces.name, type: workspaces.type, role: workspaceMembers.role }).from(workspaceMembers).innerJoin(workspaces, eq(workspaceMembers.workspaceId, workspaces.id)).where(eq(workspaceMembers.userId, req.user!.id)); return res.json({ workspaces: rows }); });
router.get("/workspaces/:workspaceId/members", async (req, res) => { const member = await membership(req.user!.id, req.params.workspaceId); if (!member) return res.status(404).json({ error: "workspace not found" }); const rows = await db.select({ id: workspaceMembers.id, userId: workspaceMembers.userId, email: users.email, username: users.username, displayName: users.displayName, role: workspaceMembers.role, permissions: workspaceMembers.permissions, joinedAt: workspaceMembers.joinedAt, lastActiveAt: workspaceMembers.lastActiveAt }).from(workspaceMembers).innerJoin(users, eq(workspaceMembers.userId, users.id)).where(eq(workspaceMembers.workspaceId, req.params.workspaceId)); return res.json({ members: rows }); });
router.post("/workspaces/:workspaceId/invitations", async (req, res) => { const manager = await manageWorkspace(req.user!.id, req.params.workspaceId); if (!manager) return res.status(403).json({ error: "workspace admin permission required" }); const email = normalizeEmail(req.body?.email); const role = typeof req.body?.role === "string" ? req.body.role : "member"; if (!EMAIL.test(email) || !ROLES.has(role) || role === "owner" || roleRank(role) >= roleRank(manager.role)) return res.status(400).json({ error: "invalid invitation" }); const [target] = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1); if (!target) return res.status(404).json({ error: "user must have a BobAI account before joining a workspace" }); if (await membership(target.id, req.params.workspaceId)) return res.status(409).json({ error: "user is already a workspace member" }); const rawToken = randomBytes(32).toString("base64url"); const tokenHash = createHash("sha256").update(rawToken).digest("hex"); const expiresAt = new Date(Date.now() + INVITE_TTL_MS); const [invite] = await db.insert(workspaceInvitations).values({ workspaceId: req.params.workspaceId, email, role, permissions: typeof req.body?.permissions === "string" ? req.body.permissions.slice(0, 1000) : null, tokenHash, invitedBy: req.user!.id, expiresAt }).onConflictDoUpdate({ target: [workspaceInvitations.workspaceId, workspaceInvitations.email], set: { role, tokenHash, invitedBy: req.user!.id, expiresAt, acceptedAt: null, revokedAt: null } }).returning({ id: workspaceInvitations.id, expiresAt: workspaceInvitations.expiresAt, email: workspaceInvitations.email, role: workspaceInvitations.role }); await recordAudit({ action: "workspace_invitation_created", resourceType: "workspace_invitation", resourceId: invite.id, userId: req.user!.id, metadata: { workspaceId: req.params.workspaceId, email, role } }); return res.status(201).json({ invitation: invite, token: rawToken }); });
router.post("/workspace-invitations/accept", async (req, res) => { const token = typeof req.body?.token === "string" ? req.body.token : ""; if (token.length < 32 || token.length > 100) return res.status(400).json({ error: "invalid invitation token" }); const tokenHash = createHash("sha256").update(token).digest("hex"); const [invite] = await db.select().from(workspaceInvitations).where(and(eq(workspaceInvitations.tokenHash, tokenHash), isNull(workspaceInvitations.acceptedAt), isNull(workspaceInvitations.revokedAt))).limit(1); if (!invite || invite.expiresAt.getTime() <= Date.now()) return res.status(400).json({ error: "invitation is invalid or expired" }); const [user] = await db.select({ id: users.id, email: users.email }).from(users).where(eq(users.id, req.user!.id)).limit(1); if (!user || user.email.toLowerCase() !== invite.email) return res.status(403).json({ error: "invitation email does not match the authenticated account" }); const existing = await membership(user.id, invite.workspaceId); if (existing) return res.status(409).json({ error: "already a workspace member" }); await db.transaction(async (tx) => { await tx.insert(workspaceMembers).values({ workspaceId: invite.workspaceId, userId: user.id, role: invite.role, permissions: invite.permissions ? { raw: invite.permissions } : null, invitedBy: invite.invitedBy }); await tx.update(workspaceInvitations).set({ acceptedAt: new Date() }).where(and(eq(workspaceInvitations.id, invite.id), isNull(workspaceInvitations.acceptedAt))); }); await recordAudit({ action: "workspace_invitation_accepted", resourceType: "workspace", resourceId: invite.workspaceId, userId: user.id }); return res.json({ joined: true, workspaceId: invite.workspaceId, role: invite.role }); });
router.delete("/workspaces/:workspaceId/invitations/:id", async (req, res) => { const manager = await manageWorkspace(req.user!.id, req.params.workspaceId); if (!manager) return res.status(403).json({ error: "workspace admin permission required" }); const [updated] = await db.update(workspaceInvitations).set({ revokedAt: new Date() }).where(and(eq(workspaceInvitations.id, req.params.id), eq(workspaceInvitations.workspaceId, req.params.workspaceId), isNull(workspaceInvitations.acceptedAt))).returning({ id: workspaceInvitations.id }); return updated ? res.status(204).send() : res.status(404).json({ error: "invitation not found" }); });
router.patch("/workspaces/:workspaceId/members/:memberId", async (req, res) => { const manager = await manageWorkspace(req.user!.id, req.params.workspaceId); if (!manager) return res.status(403).json({ error: "workspace admin permission required" }); const [target] = await db.select({ id: workspaceMembers.id, role: workspaceMembers.role, userId: workspaceMembers.userId }).from(workspaceMembers).where(and(eq(workspaceMembers.id, req.params.memberId), eq(workspaceMembers.workspaceId, req.params.workspaceId))).limit(1); if (!target || target.role === "owner" || target.userId === req.user!.id) return res.status(400).json({ error: "member cannot be changed" }); const role = typeof req.body?.role === "string" ? req.body.role : target.role; if (!ROLES.has(role) || role === "owner" || roleRank(role) >= roleRank(manager.role)) return res.status(400).json({ error: "invalid role" }); const permissions = req.body?.permissions && typeof req.body.permissions === "object" ? req.body.permissions : undefined; const [updated] = await db.update(workspaceMembers).set({ role, permissions, updatedAt: new Date() }).where(eq(workspaceMembers.id, target.id)).returning({ id: workspaceMembers.id, role: workspaceMembers.role, permissions: workspaceMembers.permissions }); return res.json(updated); });
router.delete("/workspaces/:workspaceId/members/:memberId", async (req, res) => { const manager = await manageWorkspace(req.user!.id, req.params.workspaceId); if (!manager) return res.status(403).json({ error: "workspace admin permission required" }); const [target] = await db.select({ id: workspaceMembers.id, role: workspaceMembers.role, userId: workspaceMembers.userId }).from(workspaceMembers).where(and(eq(workspaceMembers.id, req.params.memberId), eq(workspaceMembers.workspaceId, req.params.workspaceId))).limit(1); if (!target || target.role === "owner" || target.userId === req.user!.id) return res.status(400).json({ error: "member cannot be removed" }); await db.delete(workspaceMembers).where(eq(workspaceMembers.id, target.id)); return res.status(204).send(); });
router.post("/files/:fileId/shares", async (req, res) => { const [file] = await db.select({ id: uploads.id, workspaceId: uploads.workspaceId, uploadedBy: uploads.uploadedBy }).from(uploads).where(and(eq(uploads.id, req.params.fileId), isNull(uploads.deletedAt))).limit(1); if (!file) return res.status(404).json({ error: "file not found" }); const actor = await membership(req.user!.id, file.workspaceId); if (!actor) return res.status(403).json({ error: "workspace membership required" }); const owner = file.uploadedBy === req.user!.id || roleRank(actor.role) >= 3; if (!owner) return res.status(403).json({ error: "file share permission required" }); const email = normalizeEmail(req.body?.email); const permission = typeof req.body?.permission === "string" ? req.body.permission : "read"; if (!EMAIL.test(email) || !PERMISSIONS.has(permission)) return res.status(400).json({ error: "invalid file share" }); const [target] = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1); if (!target || !(await membership(target.id, file.workspaceId))) return res.status(403).json({ error: "target user is not a workspace member" }); const [share] = await db.insert(fileShares).values({ fileId: file.id, workspaceId: file.workspaceId, sharedWithUserId: target.id, permission, createdBy: req.user!.id }).onConflictDoUpdate({ target: [fileShares.fileId, fileShares.sharedWithUserId], set: { permission, updatedAt: new Date(), createdBy: req.user!.id } }).returning({ id: fileShares.id, fileId: fileShares.fileId, sharedWithUserId: fileShares.sharedWithUserId, permission: fileShares.permission }); await recordAudit({ action: "file_share_created", resourceType: "file", resourceId: file.id, userId: req.user!.id, metadata: { sharedWithUserId: target.id, permission } }); return res.status(201).json(share); });
router.get("/files/:fileId/shares", async (req, res) => { const [file] = await db.select({ id: uploads.id, workspaceId: uploads.workspaceId, uploadedBy: uploads.uploadedBy }).from(uploads).where(and(eq(uploads.id, req.params.fileId), isNull(uploads.deletedAt))).limit(1); if (!file) return res.status(404).json({ error: "file not found" }); const actor = await membership(req.user!.id, file.workspaceId); if (!actor) return res.status(403).json({ error: "file access denied" }); const [ownShare] = await db.select({ id: fileShares.id }).from(fileShares).where(and(eq(fileShares.fileId, file.id), eq(fileShares.sharedWithUserId, req.user!.id))).limit(1); if (file.uploadedBy !== req.user!.id && roleRank(actor.role) < 3 && !ownShare) return res.status(403).json({ error: "file access denied" }); const rows = await db.select({ id: fileShares.id, userId: fileShares.sharedWithUserId, email: users.email, displayName: users.displayName, permission: fileShares.permission, createdAt: fileShares.createdAt }).from(fileShares).innerJoin(users, eq(fileShares.sharedWithUserId, users.id)).where(eq(fileShares.fileId, file.id)); return res.json({ shares: rows }); });
router.delete("/files/:fileId/shares/:shareId", async (req, res) => { const [file] = await db.select({ id: uploads.id, workspaceId: uploads.workspaceId, uploadedBy: uploads.uploadedBy }).from(uploads).where(and(eq(uploads.id, req.params.fileId), isNull(uploads.deletedAt))).limit(1); if (!file) return res.status(404).json({ error: "file not found" }); const actor = await membership(req.user!.id, file.workspaceId); if (!actor || (file.uploadedBy !== req.user!.id && roleRank(actor.role) < 3)) return res.status(403).json({ error: "file share permission required" }); const [deleted] = await db.delete(fileShares).where(and(eq(fileShares.id, req.params.shareId), eq(fileShares.fileId, file.id))).returning({ id: fileShares.id }); return deleted ? res.status(204).send() : res.status(404).json({ error: "share not found" }); });
router.get("/shared-files", async (req, res) => { const rows = await db.select({ id: fileShares.id, fileId: fileShares.fileId, permission: fileShares.permission, createdAt: fileShares.createdAt, name: uploads.originalName, mimeType: uploads.mimeType, size: uploads.size, workspaceId: fileShares.workspaceId }).from(fileShares).innerJoin(uploads, eq(fileShares.fileId, uploads.id)).where(and(eq(fileShares.sharedWithUserId, req.user!.id), isNull(uploads.deletedAt))); return res.json({ files: rows }); });
export default router;
