import { randomUUID } from "node:crypto";
import { Router, type Request, type Response } from "express";
import { and, desc, eq } from "drizzle-orm";
import { db, conversations, workspaceMembers } from "@bobai/db";
import { requireAuth } from "../middleware/auth.js";
import { dbDeleteConversation, dbGetConversation, dbListConversations, dbSaveConversation } from "../store/conversationDb.js";
import { ensurePersonalWorkspace } from "../services/workspace.js";
const router = Router(); router.use(requireAuth);
type AuthenticatedRequest = Request & { user: { id: string } };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MAX_MESSAGES = 500; const MAX_MESSAGE_CONTENT = 100_000; const MAX_ATTACHMENTS_BYTES = 512_000; const MAX_CONVERSATION_BYTES = 5 * 1024 * 1024; const MAX_LABELS = 20; const MAX_LABEL_LENGTH = 50; const MAX_FOLDER_LENGTH = 100;
async function requireContext(req: AuthenticatedRequest, res: Response) { const body = req.body as Record<string, unknown> | undefined; const requested = typeof req.query.workspaceId === "string" ? req.query.workspaceId : typeof body?.workspaceId === "string" ? body.workspaceId : ""; if (!requested) { try { const workspace = await ensurePersonalWorkspace(req.user.id); return { userId: req.user.id, workspaceId: workspace.id }; } catch { res.status(503).json({ error: "personal workspace unavailable" }); return null; } } if (!UUID.test(requested)) { res.status(400).json({ error: "invalid workspace context" }); return null; } const [member] = await db.select({ id: workspaceMembers.id }).from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId, requested), eq(workspaceMembers.userId, req.user.id))).limit(1); if (!member) { res.status(403).json({ error: "workspace access denied" }); return null; } return { userId: req.user.id, workspaceId: requested }; }
function validateConversationPayload(value: Record<string, unknown>) { if (typeof value.id !== "string" || !UUID.test(value.id) || typeof value.title !== "string" || !Array.isArray(value.messages)) return "id, title, and messages are required"; if (value.messages.length > MAX_MESSAGES) return `a conversation may contain at most ${MAX_MESSAGES} messages`; let bytes = Buffer.byteLength(value.title, "utf8"); if (bytes > 800) return "title is too long"; for (const message of value.messages) { if (!message || typeof message !== "object") return "invalid message"; const item = message as Record<string, unknown>; if (typeof item.id !== "string" || !UUID.test(item.id)) return "message ids must be valid UUIDs"; if (typeof item.role !== "string" || !["user", "assistant", "system"].includes(item.role)) return "invalid message role"; if (typeof item.content !== "string" || item.content.length > MAX_MESSAGE_CONTENT) return "message content is too large"; bytes += Buffer.byteLength(item.content, "utf8"); if (item.attachments !== undefined) { let attachmentBytes = 0; try { attachmentBytes = Buffer.byteLength(JSON.stringify(item.attachments), "utf8"); } catch { return "invalid attachments"; } if (attachmentBytes > MAX_ATTACHMENTS_BYTES) return "message attachments are too large"; bytes += attachmentBytes; } if (bytes > MAX_CONVERSATION_BYTES) return "conversation payload is too large"; } return null; }
function normalizeLabels(value: unknown) { if (!Array.isArray(value)) return null; return [...new Set(value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter((item) => item && item.length <= MAX_LABEL_LENGTH).slice(0, MAX_LABELS))]; }
function normalizeFolder(value: unknown) { if (value === null) return null; if (typeof value !== "string") return undefined; const folder = value.trim(); if (!folder) return null; return folder.length <= MAX_FOLDER_LENGTH ? folder : undefined; }
router.get("/", async (req, res) => { try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; const includeArchived = req.query.archived === "true"; const limit = typeof req.query.limit === "string" && /^\d+$/.test(req.query.limit) ? Number(req.query.limit) : 50; const cursor = typeof req.query.cursor === "string" ? req.query.cursor : undefined; if (cursor && cursor.length > 200) return res.status(400).json({ error: "invalid conversation cursor" }); const rows = await dbListConversations(context.userId, context.workspaceId, includeArchived, limit, cursor); if (!rows) return res.status(503).json({ error: "persistent storage unavailable" }); return res.json({ ...rows, workspaceId: context.workspaceId }); } catch { return res.status(500).json({ error: "failed to list conversations" }); } });
router.get("/folders", async (req, res) => { try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; const rows = await db.select({ metadata: conversations.metadata }).from(conversations).where(and(eq(conversations.userId, context.userId), eq(conversations.workspaceId, context.workspaceId))).limit(5000); const folders = [...new Set(rows.flatMap((row) => { const metadata = row.metadata && typeof row.metadata === "object" && !Array.isArray(row.metadata) ? row.metadata as Record<string, unknown> : {}; return typeof metadata.folder === "string" && metadata.folder.trim() ? [metadata.folder.trim()] : []; }))].sort((a, b) => a.localeCompare(b)); return res.json({ folders }); } catch { return res.status(503).json({ error: "folder listing unavailable" }); } });
router.get("/:id", async (req, res) => { try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; if (!UUID.test(req.params.id as string)) return res.status(400).json({ error: "invalid conversation id" }); const limit = typeof req.query.limit === "string" && /^\d+$/.test(req.query.limit) ? Number(req.query.limit) : 200; const before = typeof req.query.before === "string" ? req.query.before : undefined; const conversation = await dbGetConversation(req.params.id as string, context.userId, context.workspaceId, limit, before); if (!conversation) return res.status(404).json({ error: "conversation not found" }); return res.json(conversation); } catch { return res.status(500).json({ error: "failed to get conversation" }); } });
router.post("/", async (req, res) => { const conversation = req.body as Record<string, unknown>; const validationError = validateConversationPayload(conversation); if (validationError) return res.status(400).json({ error: validationError }); try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; const saved = await dbSaveConversation({ id: conversation.id as string, userId: context.userId, workspaceId: context.workspaceId, title: (conversation.title as string).trim().slice(0, 200), messages: conversation.messages as Array<{ id?: string; role: string; content: string; model?: string | null; status?: string; attachments?: unknown }> }); if (!saved) return res.status(503).json({ error: "persistent storage unavailable" }); return res.json({ success: true, persistent: true, workspaceId: context.workspaceId }); } catch { return res.status(500).json({ error: "failed to save conversation" }); } });
router.patch("/:id", async (req, res) => { try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; const id = req.params.id as string; if (!UUID.test(id)) return res.status(400).json({ error: "invalid conversation id" }); const body = (req.body || {}) as Record<string, unknown>; const [existing] = await db.select().from(conversations).where(and(eq(conversations.id, id), eq(conversations.userId, context.userId), eq(conversations.workspaceId, context.workspaceId))).limit(1); if (!existing) return res.status(404).json({ error: "conversation not found" }); const changes: Record<string, unknown> = {}; if (typeof body.title === "string") { const title = body.title.trim(); if (!title || title.length > 200) return res.status(400).json({ error: "title must be 1-200 characters" }); changes.title = title; } if (typeof body.isPinned === "boolean") changes.isPinned = body.isPinned; if (typeof body.isArchived === "boolean") changes.isArchived = body.isArchived; const labels = normalizeLabels(body.labels); if (body.labels !== undefined && !labels) return res.status(400).json({ error: "labels must be an array of strings" }); const folder = normalizeFolder(body.folder); if (body.folder !== undefined && folder === undefined) return res.status(400).json({ error: "folder must be a string of at most 100 characters" }); if (body.labels !== undefined || body.folder !== undefined) { const currentMetadata = existing.metadata && typeof existing.metadata === "object" && !Array.isArray(existing.metadata) ? existing.metadata as Record<string, unknown> : {}; const nextMetadata = { ...currentMetadata }; if (body.labels !== undefined) { if (labels?.length) nextMetadata.labels = labels; else delete nextMetadata.labels; } if (body.folder !== undefined) { if (folder) nextMetadata.folder = folder; else delete nextMetadata.folder; } changes.metadata = nextMetadata; } if (!Object.keys(changes).length) return res.status(400).json({ error: "no supported changes supplied" }); const [updated] = await db.update(conversations).set({ ...changes, updatedAt: new Date() }).where(and(eq(conversations.id, id), eq(conversations.userId, context.userId), eq(conversations.workspaceId, context.workspaceId))).returning(); return res.json({ conversation: updated }); } catch { return res.status(503).json({ error: "conversation update unavailable" }); } });
router.post("/:id/branch", async (req, res) => { try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; const id = req.params.id as string; if (!UUID.test(id)) return res.status(400).json({ error: "invalid conversation id" }); const source = await dbGetConversation(id, context.userId, context.workspaceId); if (!source) return res.status(404).json({ error: "conversation not found" }); const branchId = randomUUID(); const title = typeof req.body?.title === "string" && req.body.title.trim() ? req.body.title.trim().slice(0, 200) : `${source.title} (branch)`; const saved = await dbSaveConversation({ id: branchId, userId: context.userId, workspaceId: context.workspaceId, title, messages: source.messages.map((message) => ({ id: randomUUID(), role: message.role, content: message.content, model: message.model, status: message.status, attachments: message.attachments })) }); if (!saved) return res.status(503).json({ error: "branch creation unavailable" }); await db.update(conversations).set({ parentConversationId: source.id, branchName: title, updatedAt: new Date() }).where(eq(conversations.id, branchId)); return res.status(201).json({ id: branchId, parentConversationId: source.id, title }); } catch { return res.status(503).json({ error: "branch creation unavailable" }); } });
router.delete("/:id", async (req, res) => { try { const context = await requireContext(req as AuthenticatedRequest, res); if (!context) return; if (!UUID.test(req.params.id as string)) return res.status(400).json({ error: "invalid conversation id" }); const deleted = await dbDeleteConversation(req.params.id as string, context.userId, context.workspaceId); if (!deleted) return res.status(404).json({ error: "conversation not found" }); return res.json({ success: true, persistent: true }); } catch { return res.status(500).json({ error: "failed to delete conversation" }); } });
export default router;
