import { Router } from "express";
import { and, eq } from "drizzle-orm";
import { db, workspaceMembers } from "@bobai/db";
import { dbRemember, dbRecallAll, dbClearMemory, dbDeleteMemory, dbUpdateMemory, isSensitiveMemory } from "../store/memoryDb.js";
import { ensurePersonalWorkspace } from "../services/workspace.js";
const router = Router();
type AuthenticatedRequest = { user?: { id: string }; query: Record<string, unknown>; body?: unknown; params: Record<string, string> };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function context(req: AuthenticatedRequest) { const body = req.body as Record<string, unknown> | undefined; const requested = typeof req.query.workspaceId === "string" ? req.query.workspaceId : typeof body?.workspaceId === "string" ? body.workspaceId : ""; const requestedProject = typeof req.query.projectId === "string" ? req.query.projectId : typeof body?.projectId === "string" ? body.projectId : ""; const userId = req.user?.id; if (!userId) return null; if (!requested) { const workspace = await ensurePersonalWorkspace(userId); return { workspaceId: workspace.id, userId, projectId: requestedProject && UUID.test(requestedProject) ? requestedProject : undefined }; } if (!UUID.test(requested)) return null; const [member] = await db.select({ id: workspaceMembers.id }).from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId, requested), eq(workspaceMembers.userId, userId))).limit(1); return member ? { workspaceId: requested, userId, projectId: requestedProject && UUID.test(requestedProject) ? requestedProject : undefined } : null; }
function validOptionalUuid(value: unknown) { return value === undefined || value === null || (typeof value === "string" && UUID.test(value)); }
function parseExpiry(value: unknown) { if (value === undefined || value === null || value === "") return null; if (typeof value !== "string") return undefined; const date = new Date(value); return Number.isNaN(date.getTime()) || date.getTime() <= Date.now() ? undefined : date; }
router.get("/", async (req, res) => { try { const ctx = await context(req as AuthenticatedRequest); if (!ctx) return res.status(403).json({ error: "workspace access denied" }); const memories = await dbRecallAll(ctx.workspaceId, ctx.userId, ctx.projectId); if (!memories) return res.status(503).json({ error: "memory storage unavailable" }); return res.json({ memories, persistent: true, workspaceId: ctx.workspaceId, projectId: ctx.projectId ?? null }); } catch { return res.status(503).json({ error: "memory storage unavailable" }); } });
router.post("/remember", async (req, res) => { const { key, value, projectId, confidence, importance, expiresAt: rawExpiry } = req.body || {}; if (typeof key !== "string" || typeof value !== "string" || !key.trim() || !value.trim() || key.length > 200 || value.length > 20_000 || !validOptionalUuid(projectId)) return res.status(400).json({ error: "valid key, value, and project are required" }); const expiresAt = parseExpiry(rawExpiry); if (rawExpiry !== undefined && expiresAt === undefined) return res.status(400).json({ error: "expiresAt must be a future ISO timestamp" }); if (isSensitiveMemory(value)) return res.status(400).json({ error: "sensitive secrets cannot be stored in memory" }); try { const ctx = await context(req as AuthenticatedRequest); if (!ctx) return res.status(403).json({ error: "workspace access denied" }); const selectedProject = typeof projectId === "string" ? projectId : ctx.projectId; if (!await dbRemember({ workspaceId: ctx.workspaceId, userId: ctx.userId, projectId: selectedProject, key: key.trim(), value: value.trim(), confidence: typeof confidence === "number" ? confidence : undefined, importance: typeof importance === "number" ? importance : undefined, expiresAt })) return res.status(503).json({ error: "memory storage unavailable" }); return res.json({ success: true, persistent: true, workspaceId: ctx.workspaceId, projectId: selectedProject ?? null }); } catch { return res.status(503).json({ error: "memory storage unavailable" }); } });
router.patch("/:id", async (req, res) => { try { const ctx = await context(req as AuthenticatedRequest); if (!ctx || !UUID.test(req.params.id)) return res.status(400).json({ error: "valid memory id is required" }); const body = (req.body || {}) as Record<string, unknown>; const changes: { category?: string; content?: string; isPinned?: boolean; isArchived?: boolean; importance?: number; confidence?: number; expiresAt?: Date | null } = {}; if (typeof body.category === "string") changes.category = body.category.trim().slice(0, 200); if (typeof body.content === "string") { if (!body.content.trim() || body.content.length > 20_000 || isSensitiveMemory(body.content)) return res.status(400).json({ error: "invalid or sensitive memory content" }); changes.content = body.content.trim(); } if (typeof body.isPinned === "boolean") changes.isPinned = body.isPinned; if (typeof body.isArchived === "boolean") changes.isArchived = body.isArchived; if (typeof body.importance === "number" && Number.isFinite(body.importance)) changes.importance = Math.max(0, Math.min(100, Math.round(body.importance))); if (typeof body.confidence === "number" && Number.isFinite(body.confidence)) changes.confidence = Math.max(0, Math.min(100, Math.round(body.confidence))); if (body.expiresAt !== undefined) { const expiresAt = parseExpiry(body.expiresAt); if (body.expiresAt !== null && expiresAt === undefined) return res.status(400).json({ error: "expiresAt must be null or a future ISO timestamp" }); changes.expiresAt = expiresAt; } if (!Object.keys(changes).length) return res.status(400).json({ error: "no supported changes supplied" }); const memory = await dbUpdateMemory(req.params.id, ctx.workspaceId, ctx.userId, changes); if (!memory) return res.status(404).json({ error: "memory not found" }); return res.json({ memory }); } catch { return res.status(503).json({ error: "memory update unavailable" }); } });
router.delete("/:id", async (req, res) => { try { const ctx = await context(req as AuthenticatedRequest); if (!ctx || !UUID.test(req.params.id)) return res.status(400).json({ error: "valid memory id is required" }); if (!await dbDeleteMemory(req.params.id, ctx.workspaceId, ctx.userId)) return res.status(404).json({ error: "memory not found" }); return res.json({ success: true }); } catch { return res.status(503).json({ error: "memory deletion unavailable" }); } });
router.delete("/", async (req, res) => { try { const ctx = await context(req as AuthenticatedRequest); if (!ctx) return res.status(403).json({ error: "workspace access denied" }); if (!await dbClearMemory(ctx.workspaceId, ctx.userId, ctx.projectId)) return res.status(503).json({ error: "memory storage unavailable" }); return res.json({ success: true, persistent: true }); } catch { return res.status(503).json({ error: "memory storage unavailable" }); } });
export default router;
