import { Router } from "express";
import { and, desc, eq, isNull } from "drizzle-orm";
import { db, notifications } from "@bobai/db";
const router = Router();
router.get("/", async (req, res) => { try { const userId = req.user?.id; if (!userId) return res.status(401).json({ error: "authentication required" }); const rows = await db.select().from(notifications).where(and(eq(notifications.userId, userId), isNull(notifications.archivedAt))).orderBy(desc(notifications.createdAt)).limit(100); return res.json({ notifications: rows }); } catch { return res.status(503).json({ error: "notifications unavailable" }); } });
router.post("/:id/read", async (req, res) => { try { const userId = req.user?.id; const id = req.params.id as string; if (!userId) return res.status(401).json({ error: "authentication required" }); const [row] = await db.update(notifications).set({ isRead: true, readAt: new Date(), updatedAt: new Date() }).where(and(eq(notifications.id, id), eq(notifications.userId, userId))).returning({ id: notifications.id }); if (!row) return res.status(404).json({ error: "notification not found" }); return res.json({ success: true }); } catch { return res.status(503).json({ error: "notification update unavailable" }); } });
router.post("/read-all", async (req, res) => { try { const userId = req.user?.id; if (!userId) return res.status(401).json({ error: "authentication required" }); await db.update(notifications).set({ isRead: true, readAt: new Date(), updatedAt: new Date() }).where(and(eq(notifications.userId, userId), eq(notifications.isRead, false), isNull(notifications.archivedAt))); return res.json({ success: true }); } catch { return res.status(503).json({ error: "notification update unavailable" }); } });
router.delete("/:id", async (req, res) => { try { const userId = req.user?.id; const id = req.params.id as string; if (!userId) return res.status(401).json({ error: "authentication required" }); const [row] = await db.update(notifications).set({ archivedAt: new Date(), updatedAt: new Date() }).where(and(eq(notifications.id, id), eq(notifications.userId, userId))).returning({ id: notifications.id }); if (!row) return res.status(404).json({ error: "notification not found" }); return res.json({ success: true }); } catch { return res.status(503).json({ error: "notification archive unavailable" }); } });
export default router;
