import { Router } from "express";
import { and, asc, eq, gt, isNull } from "drizzle-orm";
import { db, reminders, workspaceMembers } from "@bobai/db";
import { ensurePersonalWorkspace } from "../services/workspace.js";

const router = Router();
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function context(userId: string, requested?: string) {
  if (!requested) { const workspace = await ensurePersonalWorkspace(userId); return workspace.id; }
  if (!UUID.test(requested)) return null;
  const [member] = await db.select({ id: workspaceMembers.id }).from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId, requested), eq(workspaceMembers.userId, userId))).limit(1);
  return member ? requested : null;
}
function validDate(value: unknown) { if (typeof value !== "string") return null; const date = new Date(value); return Number.isFinite(date.getTime()) ? date : null; }

router.get("/", async (req, res) => { try { const userId = req.user?.id; if (!userId) return res.status(401).json({ error: "authentication required" }); const workspaceId = await context(userId, typeof req.query.workspaceId === "string" ? req.query.workspaceId : undefined); if (!workspaceId) return res.status(403).json({ error: "workspace access denied" }); const rows = await db.select().from(reminders).where(and(eq(reminders.userId, userId), eq(reminders.workspaceId, workspaceId), isNull(reminders.deletedAt))).orderBy(asc(reminders.remindAt)); return res.json({ reminders: rows }); } catch { return res.status(503).json({ error: "reminder storage unavailable" }); } });
router.post("/", async (req, res) => { try { const userId = req.user?.id; if (!userId) return res.status(401).json({ error: "authentication required" }); const body = (req.body || {}) as Record<string, unknown>; const title = typeof body.title === "string" ? body.title.trim() : ""; const remindAt = validDate(body.remindAt); if (!title || title.length > 200 || !remindAt || remindAt.getTime() <= Date.now()) return res.status(400).json({ error: "title and a future remindAt are required" }); const workspaceId = await context(userId, typeof body.workspaceId === "string" ? body.workspaceId : undefined); if (!workspaceId) return res.status(403).json({ error: "workspace access denied" }); const message = typeof body.message === "string" ? body.message.trim().slice(0, 5000) : null; const timezone = typeof body.timezone === "string" && body.timezone.length <= 80 ? body.timezone : "UTC"; const recurrenceRule = typeof body.recurrenceRule === "string" && body.recurrenceRule.length <= 500 ? body.recurrenceRule : null; const [reminder] = await db.insert(reminders).values({ workspaceId, userId, title, message, remindAt, timezone, recurrenceRule, channels: Array.isArray(body.channels) ? body.channels.slice(0, 5) : ["in_app"] }).returning(); return res.status(201).json({ reminder }); } catch { return res.status(503).json({ error: "reminder creation unavailable" }); } });
router.patch("/:id", async (req, res) => { try { const userId = req.user?.id; const id = req.params.id as string; if (!userId || !UUID.test(id)) return res.status(400).json({ error: "valid reminder id is required" }); const body = (req.body || {}) as Record<string, unknown>; const changes: Record<string, unknown> = {}; if (typeof body.title === "string") changes.title = body.title.trim().slice(0, 200); if (typeof body.message === "string") changes.message = body.message.slice(0, 5000); if (typeof body.isCompleted === "boolean") changes.isCompleted = body.isCompleted; if (body.remindAt !== undefined) { const date = validDate(body.remindAt); if (!date || date.getTime() <= Date.now()) return res.status(400).json({ error: "remindAt must be a future date" }); changes.remindAt = date; } if (!Object.keys(changes).length) return res.status(400).json({ error: "no supported changes supplied" }); const [updated] = await db.update(reminders).set({ ...changes, updatedAt: new Date() }).where(and(eq(reminders.id, id), eq(reminders.userId, userId), isNull(reminders.deletedAt))).returning(); if (!updated) return res.status(404).json({ error: "reminder not found" }); return res.json({ reminder: updated }); } catch { return res.status(503).json({ error: "reminder update unavailable" }); } });
router.delete("/:id", async (req, res) => { try { const userId = req.user?.id; const id = req.params.id as string; if (!userId || !UUID.test(id)) return res.status(400).json({ error: "valid reminder id is required" }); const [deleted] = await db.update(reminders).set({ deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(reminders.id, id), eq(reminders.userId, userId), isNull(reminders.deletedAt))).returning({ id: reminders.id }); if (!deleted) return res.status(404).json({ error: "reminder not found" }); return res.json({ success: true }); } catch { return res.status(503).json({ error: "reminder deletion unavailable" }); } });
router.get("/upcoming", async (req, res) => { try { const userId = req.user?.id; if (!userId) return res.status(401).json({ error: "authentication required" }); const workspaceId = await context(userId, typeof req.query.workspaceId === "string" ? req.query.workspaceId : undefined); if (!workspaceId) return res.status(403).json({ error: "workspace access denied" }); const rows = await db.select().from(reminders).where(and(eq(reminders.userId, userId), eq(reminders.workspaceId, workspaceId), gt(reminders.remindAt, new Date()), isNull(reminders.deletedAt))).orderBy(asc(reminders.remindAt)).limit(50); return res.json({ reminders: rows }); } catch { return res.status(503).json({ error: "reminder storage unavailable" }); } });
export default router;
