#define NAPI_VERSION 8
#include <node_api.h>
#include <piper.h>
#include <whisper.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

static napi_value Fail(napi_env env, const char *message) { napi_throw_error(env, nullptr, message); return nullptr; }
static bool StringArg(napi_env env, napi_value value, std::string &out) { size_t size = 0; if (napi_get_value_string_utf8(env, value, nullptr, 0, &size) != napi_ok) return false; out.resize(size); return napi_get_value_string_utf8(env, value, out.data(), size + 1, &size) == napi_ok; }
static bool BufferArg(napi_env env, napi_value value, void **data, size_t *length) { return napi_get_buffer_info(env, value, data, length) == napi_ok; }
static void put16(std::vector<uint8_t> &out, uint16_t v) { out.push_back(v & 255); out.push_back((v >> 8) & 255); }
static void put32(std::vector<uint8_t> &out, uint32_t v) { for (int i = 0; i < 4; ++i) out.push_back((v >> (8 * i)) & 255); }
static std::vector<uint8_t> makeWav(const std::vector<float> &samples, int sampleRate) { std::vector<uint8_t> out; out.reserve(44 + samples.size() * 2); out.insert(out.end(), {'R','I','F','F'}); put32(out, 36 + static_cast<uint32_t>(samples.size() * 2)); out.insert(out.end(), {'W','A','V','E','f','m','t',' '}); put32(out, 16); put16(out, 1); put16(out, 1); put32(out, sampleRate); put32(out, static_cast<uint32_t>(sampleRate * 2)); put16(out, 2); put16(out, 16); out.insert(out.end(), {'d','a','t','a'}); put32(out, static_cast<uint32_t>(samples.size() * 2)); for (float sample : samples) { const float clamped = std::max(-1.0f, std::min(1.0f, sample)); const int16_t value = static_cast<int16_t>(std::lrint(clamped * 32767.0f)); put16(out, static_cast<uint16_t>(value)); } return out; }
static bool readWav(const uint8_t *data, size_t size, std::vector<float> &mono, int &sampleRate) { if (size < 44 || std::memcmp(data, "RIFF", 4) || std::memcmp(data + 8, "WAVE", 4)) return false; size_t pos = 12; uint16_t channels = 0, bits = 0, format = 0; uint32_t rate = 0; const uint8_t *pcm = nullptr; size_t pcmSize = 0; while (pos + 8 <= size) { const uint32_t chunkSize = data[pos+4] | (data[pos+5] << 8) | (data[pos+6] << 16) | (data[pos+7] << 24); if (std::memcmp(data + pos, "fmt ", 4) == 0 && chunkSize >= 16 && pos + 8 + chunkSize <= size) { format = data[pos+8] | (data[pos+9] << 8); channels = data[pos+10] | (data[pos+11] << 8); rate = data[pos+12] | (data[pos+13] << 8) | (data[pos+14] << 16) | (data[pos+15] << 24); bits = data[pos+22] | (data[pos+23] << 8); } else if (std::memcmp(data + pos, "data", 4) == 0 && pos + 8 + chunkSize <= size) { pcm = data + pos + 8; pcmSize = chunkSize; } pos += 8 + chunkSize + (chunkSize & 1); } if (format != 1 || !pcm || channels < 1 || channels > 2 || bits != 16 || rate == 0 || pcmSize % (2 * channels)) return false; const size_t frames = pcmSize / (2 * channels); mono.resize(frames); for (size_t i = 0; i < frames; ++i) { float sum = 0; for (uint16_t c = 0; c < channels; ++c) { const size_t p = (i * channels + c) * 2; const int16_t v = static_cast<int16_t>(pcm[p] | (pcm[p+1] << 8)); sum += static_cast<float>(v) / 32768.0f; } mono[i] = sum / channels; } sampleRate = static_cast<int>(rate); return true; }
static std::vector<float> resample(const std::vector<float> &input, int from, int to) { if (from == to) return input; const size_t outputSize = static_cast<size_t>(std::ceil(input.size() * static_cast<double>(to) / from)); std::vector<float> output(outputSize); for (size_t i = 0; i < outputSize; ++i) { const double source = i * static_cast<double>(from) / to; const size_t a = std::min(input.size() - 1, static_cast<size_t>(source)); const size_t b = std::min(input.size() - 1, a + 1); const float f = static_cast<float>(source - a); output[i] = input[a] * (1 - f) + input[b] * f; } return output; }

static napi_value Synthesize(napi_env env, napi_callback_info info) { size_t argc = 5; napi_value argv[5]; if (napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr) != napi_ok || argc < 4) return Fail(env, "BobVoice requires modelPath, configPath, espeakDataPath and text"); std::string model, config, espeak, text; if (!StringArg(env, argv[0], model) || !StringArg(env, argv[1], config) || !StringArg(env, argv[2], espeak) || !StringArg(env, argv[3], text)) return Fail(env, "invalid BobVoice argument"); piper_synthesizer *synth = piper_create(model.c_str(), config.empty() ? nullptr : config.c_str(), espeak.c_str()); if (!synth) return Fail(env, "Piper could not load the voice model"); piper_synthesize_options options = piper_default_synthesize_options(synth); if (argc >= 5) { double scale = 1; if (napi_get_value_double(env, argv[4], &scale) == napi_ok) options.length_scale = static_cast<float>(std::clamp(scale, 0.5, 2.0)); } if (piper_synthesize_start(synth, text.c_str(), &options) != PIPER_OK) { piper_free(synth); return Fail(env, "Piper synthesis could not start"); } std::vector<float> samples; int rate = 22050; piper_audio_chunk chunk{}; while (true) { const int status = piper_synthesize_next(synth, &chunk); if (status == PIPER_DONE) break; if (status != PIPER_OK) { piper_free(synth); return Fail(env, "Piper synthesis failed"); } if (chunk.sample_rate > 0) rate = chunk.sample_rate; samples.insert(samples.end(), chunk.samples, chunk.samples + chunk.num_samples); } piper_free(synth); const auto wav = makeWav(samples, rate); napi_value result; void *buffer = nullptr; if (napi_create_buffer_copy(env, wav.size(), wav.data(), &buffer, &result) != napi_ok) return Fail(env, "could not create audio buffer"); return result; }

static napi_value Transcribe(napi_env env, napi_callback_info info) { size_t argc = 3; napi_value argv[3]; if (napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr) != napi_ok || argc < 2) return Fail(env, "BobWhisper requires modelPath and WAV buffer"); std::string model; if (!StringArg(env, argv[0], model)) return Fail(env, "invalid Whisper model path"); void *data = nullptr; size_t size = 0; if (!BufferArg(env, argv[1], &data, &size) || size > 25 * 1024 * 1024) return Fail(env, "invalid Whisper audio buffer"); std::vector<float> samples; int rate = 0; if (!readWav(static_cast<uint8_t *>(data), size, samples, rate)) return Fail(env, "BobWhisper currently accepts PCM16 WAV input"); samples = resample(samples, rate, WHISPER_SAMPLE_RATE); whisper_context_params contextParams = whisper_context_default_params(); contextParams.use_gpu = false; whisper_context *ctx = whisper_init_from_file_with_params(model.c_str(), contextParams); if (!ctx) return Fail(env, "Whisper model could not be loaded"); whisper_full_params params = whisper_full_default_params(WHISPER_SAMPLING_GREEDY); params.n_threads = 4; if (argc >= 3) { int32_t threads = 4; if (napi_get_value_int32(env, argv[2], &threads) == napi_ok) params.n_threads = std::clamp(threads, 1, 16); } const int resultCode = whisper_full(ctx, params, samples.data(), static_cast<int>(samples.size())); if (resultCode != 0) { whisper_free(ctx); return Fail(env, "Whisper transcription failed"); } std::string text; const int count = whisper_full_n_segments(ctx); for (int i = 0; i < count; ++i) text += whisper_full_get_segment_text(ctx, i); whisper_free(ctx); napi_value result; napi_create_string_utf8(env, text.c_str(), text.size(), &result); return result; }

static napi_value ProbeWav(napi_env env, napi_callback_info info) { size_t argc = 1; napi_value argv[1]; if (napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr) != napi_ok || argc < 1) return Fail(env, "BobMedia probe requires a buffer"); void *data = nullptr; size_t size = 0; if (!BufferArg(env, argv[0], &data, &size)) return Fail(env, "invalid media buffer"); std::vector<float> samples; int rate = 0; if (!readWav(static_cast<uint8_t *>(data), size, samples, rate)) return Fail(env, "unsupported media container: native BobMedia currently supports PCM16 WAV"); napi_value result; napi_create_object(env, &result); napi_value value; napi_create_string_utf8(env, "wav", NAPI_AUTO_LENGTH, &value); napi_set_named_property(env, result, "format", value); napi_create_int32(env, rate, &value); napi_set_named_property(env, result, "sampleRate", value); napi_create_uint32(env, static_cast<uint32_t>(samples.size()), &value); napi_set_named_property(env, result, "samples", value); return result; }
static napi_value Status(napi_env env, napi_callback_info info) { napi_value result; napi_create_object(env, &result); napi_value value; napi_get_boolean(env, true, &value); napi_set_named_property(env, result, "native", value); napi_create_string_utf8(env, whisper_version(), NAPI_AUTO_LENGTH, &value); napi_set_named_property(env, result, "whisperVersion", value); napi_create_string_utf8(env, "piper-libpiper", NAPI_AUTO_LENGTH, &value); napi_set_named_property(env, result, "voiceEngine", value); napi_create_string_utf8(env, "pcm16-wav", NAPI_AUTO_LENGTH, &value); napi_set_named_property(env, result, "mediaFormats", value); return result; }

NAPI_MODULE_INIT() { napi_value fn; napi_create_function(env, "synthesize", NAPI_AUTO_LENGTH, Synthesize, nullptr, &fn); napi_set_named_property(env, exports, "synthesize", fn); napi_create_function(env, "transcribe", NAPI_AUTO_LENGTH, Transcribe, nullptr, &fn); napi_set_named_property(env, exports, "transcribe", fn); napi_create_function(env, "probeWav", NAPI_AUTO_LENGTH, ProbeWav, nullptr, &fn); napi_set_named_property(env, exports, "probeWav", fn); napi_create_function(env, "status", NAPI_AUTO_LENGTH, Status, nullptr, &fn); napi_set_named_property(env, exports, "status", fn); return exports; }
