import type { ChatMessage, Conversation } from "@/types/chat";
import { clearSession, getSession, refreshSession } from "@/lib/auth";
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001";
async function request(path: string, init: RequestInit = {}, retry = true) { const headers = new Headers(init.headers); headers.set("Content-Type", "application/json"); const session = getSession(); if (session?.accessToken) headers.set("Authorization", `Bearer ${session.accessToken}`); let res = await fetch(`${API}${path}`, { ...init, headers }); if (res.status === 401 && retry && session?.refreshToken) { const refreshed = await refreshSession(); if (refreshed?.accessToken) { const retryHeaders = new Headers(init.headers); retryHeaders.set("Content-Type", "application/json"); retryHeaders.set("Authorization", `Bearer ${refreshed.accessToken}`); res = await fetch(`${API}${path}`, { ...init, headers: retryHeaders }); } else clearSession(); } return res; }
export async function sendMessage(messages: ChatMessage[], personality = "", modelId?: string) { const cleanMessages = messages.map((m) => ({ role: m.role, content: m.content })); const res = await request("/chat", { method: "POST", body: JSON.stringify({ messages: cleanMessages, personality, ...(modelId ? { modelId } : {}) }) }); if (!res.ok) throw new Error((await res.text()) || "Failed to send message"); return res.json(); }
export async function listConversations(): Promise<Conversation[]> { const res = await request("/conversations"); if (!res.ok) throw new Error((await res.text()) || "Failed to load conversations"); const data = await res.json() as { conversations?: Array<Record<string, unknown>> }; return (data.conversations || []).map((conversation) => ({ id: String(conversation.id), title: typeof conversation.title === "string" ? conversation.title : "new chat", createdAt: new Date(String(conversation.createdAt || Date.now())).getTime(), pinned: false, messages: Array.isArray(conversation.messages) ? conversation.messages.map((message) => { const item = message as Record<string, unknown>; const attachments = item.attachments as Record<string, unknown> | null; return { id: String(item.id), role: item.role === "assistant" ? "assistant" as const : "user" as const, content: typeof item.content === "string" ? item.content : "", ...(attachments && typeof attachments === "object" ? attachments : {}) }; }) : [] })); }
export async function saveConversation(conversation: Conversation) { const res = await request("/conversations", { method: "POST", body: JSON.stringify({ id: conversation.id, title: conversation.title, messages: conversation.messages.map((message) => ({ id: message.id, role: message.role, content: message.content, status: "completed", attachments: { ...(message.images?.length ? { images: message.images } : {}), ...(message.files?.length ? { files: message.files } : {}), ...(message.pinned ? { pinned: true } : {}) } })) }) }); if (!res.ok) throw new Error((await res.text()) || "Failed to save conversation"); }
export async function deleteConversation(conversationId: string) { const res = await request(`/conversations/${encodeURIComponent(conversationId)}`, { method: "DELETE" }); if (!res.ok && res.status !== 404) throw new Error((await res.text()) || "Failed to delete conversation"); }
export async function generateImage(prompt: string) { const res = await request("/images/generate", { method: "POST", body: JSON.stringify({ prompt, count: 4, width: 1024, height: 1024 }) }); if (!res.ok) throw new Error((await res.text()) || "Failed to generate image"); return res.json(); }
export async function uploadFile(file: File, onProgress?: (progress: number) => void) { const form = new FormData(); form.append("file", file); const session = getSession(); return new Promise<{ name: string; type: string; text: string }>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open("POST", `${API}/files/upload`); if (session?.accessToken) xhr.setRequestHeader("Authorization", `Bearer ${session.accessToken}`); xhr.upload.onprogress = (e) => { if (e.lengthComputable && onProgress) onProgress(Math.round((e.loaded / e.total) * 100)); }; xhr.onload = () => { if (xhr.status >= 200 && xhr.status < 300) { try { resolve(JSON.parse(xhr.responseText)); } catch { reject(new Error("Invalid upload response")); } } else reject(new Error(xhr.responseText || "Upload failed")); }; xhr.onerror = () => reject(new Error("Upload failed")); xhr.send(form); }); }
export async function runCodingAgent(task: string) { const res = await request("/agents/run", { method: "POST", body: JSON.stringify({ task }) }); const result = await res.json(); if (!res.ok) throw new Error(result.error || "Coding agent failed"); return result as { output: string; warnings: string }; }
